### ISSUE TITLE
Expose batch_size for predict and predict_proba

### ISSUE THREAD

**Issue by lspracklen** [amaiya/ktrain#103]
Hey!

  Really enjoying using ktrain -- makes life so much easier!

  I'm currently using BERT on shortish sentences and have been looking at decreasing the max sequence length. At present, I'm able to control the batch_size for training, and see significant reductions in training time for smaller sequence lengths.

 For inference, I didn't see any real performance improvement. I see that the ktrain predict() is a wrapper around Keras, and that Keras predict takes a batch size argument.

 I tried some simple experiments by modifying ktrain and passing down a batch_size argument to Keras. For my large inference jobs, using a GPU, I saw a 3X reduction in wall-clock time.

 I was wondering whether this functionality might be something you would be willing to add to ktrain?

Thanks in advance

Lawrence

**Comment by amaiya** [comment]
Hello,

Great idea.  I'm in complete agreement that there should be a way to control the `batch_size` for testing and evaluation separate and apart from the training `batch_size`.  As of right now, there is a single `batch_size` parameter that is used for both.  

However, passing `batch_size` to `model.predict` will not work, as noted in the TF documentation:
```
        batch_size: Integer or `None`.
            Number of samples per gradient update.
            If unspecified, `batch_size` will default to 32.
            Do not specify the `batch_size` if your data is in the
            form of symbolic tensors, dataset,
            generators, or `keras.utils.Sequence` instances (since they generate
            batches).
```
So, for transformer models that use tf.Datasets on the backend or models that use `utils.Sequence` or generators, supplying `batch_size` to `predict` won't work.  I think it worked in your case because the original BERT implementation in *ktrain* (accessed via `text_classifier` function) represents inputs as arrays.

I will mark this issue as an enhancement request to be added in a future release and create an `eval_batch_size` parameter so that predictions can be configured to use a different batch_size.


Thanks.

- Arun

**Comment by amaiya** [comment]
In v0.12.0, the `get_predictor` and `load_predictor` functions each have a `batch_size` argument that will be used for predictions.  In addition, the `get_learner` function now has an `eval_batch_size` parameter.  

If you find issues with any of this, please reply to this thread or open a new issue.  I will close this issue for now.

Thanks for posting.
