### ISSUE TITLE
Multi feature text classification

### ISSUE THREAD

**Issue by Niekvdplas** [amaiya/ktrain#110]
Hello,

For my research I want to classify on two columns, I'll explain why. I work with data from municipalities to classify issues to their category. However, every municipality has the right to name its own categories. So say street-lighting in one is called lighting in another. An example:

"The whole neighbourhood is in the dark because the lights are off." in Amsterdam this might be classified as 'Street-lighting' but in New York this is 'Lighting'.

As you can see the city is important to know which class to choose. Now I have enough data per municipality and per category so there is no issue there. My question is how can I select multiple columns for my x variable. Currently I do this:

def get_datasets(X, y):
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    x_train, x_test, y_train, y_test = x_train.to_numpy(), x_test.to_numpy(), y_train.to_numpy(), y_test.to_numpy()
    return x_train, x_test, y_train, y_test

X = data['IssueDescription', 'address']
y = data['CategoryShort']

x_train, x_test, y_train, y_test = get_datasets(X, y)

t = text.Transformer(args.modelname, maxlen=args.maxlen, class_names=categories)

t.lang = 'nl'

y_train, y_test = index_set(y_train, y_test)

trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)

However this results in an error:
Traceback (most recent call last):
  File ".\multifeature.py", line 99, in <module>
    X = data['IssueDescription', 'address']
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('IssueDescription', 'address')

What am I forgetting?

**Comment by amaiya** [comment]
Transformer models only accept preprocessed text as input (input_ids).  If you really want to treat the city as an extra categorical field combined with text input, then you can try something like what is shown in [tutorial A4](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb).  The basic idea is two create two models: a text classifier that accepts text input and another model that accepts a categorical field and outputs an embedding.  The categorical embedding and text classifier output can be combined via a Dense layer (and perhaps Dropout, etc.) to produce the final output.  Note, however, the `t.get_classifier` method in *ktrain* produces a `TFBertForSequenceClassification` model (when a `bert-*` model is selected for example), and, in TensorFlow2, it does not appear to be possible to obtain intermediate output from a transformer model (which uses the Subclassing API, I believe).   So, instead of using the model returned by `t.get_classifier`, you can use `BertModel` (or DistilBertModel for DistilBert, etc.).  You can take the CLS embedding from the transformer model and combine it (perhaps via concatenation) with the city embedding and run things through a final Dense layer to produce the final classification. To do this, you'll also need to wrap your data (which yields two inputs - the text and the city/address) in a `ktrain.Dataset` class, which is shown in [tutorial A4](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb).  There are also some other simpler alternatives that may or may not make sense to try.

Here are some different options:

1. As described above, try replacing the model returned by `t.get_classifier()` with a `*Model`, where `*` is whichever transformer model you're using (e.g., BertModel, DistilBertModel, etc.) and combining this with another model that accepts the extra predictors as inputs
2. Treating `address` as text and concatenate with the `IssueDescription` into a single text field and feed that as input to a Transformer model normally
3. Train a separate model for each city that accepts only `issueDescription` as input.  Use the extracted city (from address field) to select the model to use when making a prediction
4.  Manually preprocess the `CategoryShort` field to merge labels that mean the same thing, so that all cities use the same set of labels (`street-lighting` and `lighting` would be merged into a single `lighting` label, for example).  Then, train as normal using only the text as input.
5. Represent the problem as a multilabel problem, so that if `issueDescription` indicates that it is a problem with street lights, then both the `street-lighting` and `lighting` should be activated
