### ISSUE TITLE
Selection of a specific BERT pretrained model

### ISSUE THREAD

**Issue by emanueledirosa** [amaiya/ktrain#12]
Hi Amaiya,
it's a great project! Congrats!
However, I'd like to specify which specific BERT pretrained model to use.
For example, I'd like to try the last Multilingual Cased, but I don't see in the documentation how to do that.
I guess It might be an option in this call:
txt.text_classifier('bert', (x_train, y_train))

Thank you in advance.
Cheers,
Emanuele

**Comment by amaiya** [comment]
Hello:  Several people have requested this.  This can be added to future release, and I agree that it should be an option in `text_classifier`.  

If I push an experimental branch to GitHub with this feature, would you be willing to install and test it with your language of interest?

**Comment by emanueledirosa** [comment]
Yes, with pleasure. :)
thanks

**Comment by Krids** [comment]
I am using ktrain in portuguese. But I`m facing some issues like in the load_predictor asking for some gelu tensorflow but I don't find anything about that on google.

**Comment by amaiya** [comment]
@Krids The issue with `load_predictor` complaining about `gelu_tensorflow` was fixed a while ago.  This should work with the latest version of *ktrain*, so please upgrade to the latest version.  If you still have trouble, then please open a new issue with more details including code.  On a side note, the next version of *ktrain* (to be released soon) provides better support for non-English languages for all text classification models including BERT.

**Comment by amaiya** [comment]
@emanueledirosa 

*ktrain* v0.4.0, which was just released, attempts to provide support for multilingual text classification for all models including BERT.  In the case of BERT, if a non-English language is detected, then the multilingual-cased BERT model will be downloaded (instead of the English-only model).    See this example notebook for an example of building a sentiment analysis model for Chinese:

[ChineseHotelReviews-BERT.ipynb](https://github.com/amaiya/ktrain/blob/master/examples/text/ChineseHotelReviews-BERT.ipynb)


As you'll see in the notebook, an attempt has been made to make this completely automated.   *ktrain* will attempt to detect the language and character encoding and prepare the data and configure the model appropriately.  However, it was only tested on a single non-English corpus (i.e., the Chinese corpus above).  

If you find a problem/bug when testing this on your language of interest, please open an issue about it with details. Thanks.

**Comment by amaiya** [comment]
@emanueledirosa 
There was a bug in 0.4.0 with multilingual BERT.  Please be sure to use ktrain v0.4.1+ if using BERT on non-English corpus.
