### ISSUE TITLE
Multilabel Confusion Matrices Not Supported

### ISSUE THREAD

**Issue by NicoleJaneway** [amaiya/ktrain#120]
Working on a text classification problem.  

Running this code:

```
ft_cols = list(data.columns)
ft_cols.remove(TEXT_COL)
[train/test split, add model, add learner, fit learner...]
learner.validate(class_names=ft_cols)

```
...I get the following error:

> /usr/local/lib/python3.6/dist-packages/ktrain/core.py:86: UserWarning: multilabel confusion matrices not yet supported
>   warnings.warn('multilabel confusion matrices not yet supported')

It's the same if I call...

`learner.validate(class_names=t.get_classes())`

...as per the example on the GitHub ktrain homepage using  Hugging Face Transformers on 20 Newsgroups Dataset.  And that definitely looks like more than 2 categories.  

Any suggestions?

**Comment by amaiya** [comment]
Hello:  The `validate` method works on the 20newsgroup dataset, as illustrated in [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb).  Although the 20newsgroups dataset has more than 2 classes, it is not a multilabel problem because the classes are mutually exclusive (i.e., each document can belong to only a single newsgroup).

I suspect that there might be a bug in your data-loading process taking place prior to inserting data into *ktrain*.  The multilabel error basically is saying that *ktrain* inspected your data and found that  the labels are not mutually exclusive.  So, if there were only four newsgroup categories, then the y_train and  y_test (after preprocsssing) should look something like this:
```
[0 0 0 1]
[1 0 0 0]
[0 1 0 0]
```

...instead *ktrain* found that at least one example was assigned to 2 or more newsgroups in error:
```
[ 1 1 0 0]
```
Are you sure `ft_columns` contains labels for the 20newsgroup dataset?

If you post your full code showing what `ft_columns` contains and how it is created, it may shed more light on what is happening.

**Comment by amaiya** [comment]
I edited the original response because I mistakenly thought you were getting this error with some version of the 20newsgroup dataset.  The gist of the answer is the same, though.  If you inspect your labels in the dataset and find that examples are assigned to more than one category (either correctly or incorrectly), this is the reason for the error. 

That said, there is now support for multilabel confusion matrices and classification reports in sklearn, so this can probably be supported in future.

**Comment by NicoleJaneway** [comment]
Hey Arun,

Thanks very much for the speedy reply (and for the awesome tool - much appreciated!)

Ah, so the labels are not mutually exclusive.  Let me clean up that element of the dataset, then report back whether `validate` works.

**Comment by NicoleJaneway** [comment]
Works with mutually exclusive columns
