### ISSUE TITLE
Enhancement : Support for pre-training pre-trained models

### ISSUE THREAD

**Issue by saishashank85** [amaiya/ktrain#131]
Support for pre-training pre-trained models

**Comment by amaiya** [comment]
Thanks - tagged as enhancement request.

**Comment by talhaanwarch** [comment]
waiting for this

**Comment by amaiya** [comment]
Hello,

It should be easy to pretrain language models (either fine-tuning them or train from scratch) for use with **ktrain** using the steps described in [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-pretrain-a-language-model-for-use-with-ktrain) (thanks to support scripts provided directly by Hugging Face).

Since  it is already easy to do this and many **ktrain** users are evidently already successfully pretraining language models using the steps described above, I wasn't planning to add additional wrappers for this.   I will close this issue, But, if you have any problems following the steps described in the FAQ, feel free to open a new issue.
