### ISSUE TITLE
During training BERT I would like to use sample_weights features which is provided by keras but i dont kow how to apply sample_weights using Ktrain. This is very important to me to use sample_weights during training ? Plz help me

### ISSUE THREAD

**Issue by aadityachapagain** [amaiya/ktrain#142]

**Comment by amaiya** [comment]
If you want to use the `sample_weight` parameter, you'll have to access the Keras API directly with this: `learner.model.fit` instead of `learner.fit` or `learner.fit_onecycle`, etc.   Even then, it will only work if you created your BERT model with `text_classifier('bert',...)`.   This is because the `sample_weight` parameter in Keras is only for training data in the form of arrays.  For data in the form of generators and sequences, you must add a third value to generated tuples for sample weights. 

For imbalanced datasets, there is a `class_weight` argument in `learner.fit`, `learner.autofit`, and `learner.fit_onecycle` though, if that's what you were really l
