### ISSUE TITLE
Multilabel is working?

### ISSUE THREAD

**Issue by Guillermogsjc** [amaiya/ktrain#154]
Hi,

firstly congratulations, the library is absolutely awesome and working very fine.

One issue that I just found is that despite having stablished `multilabel=True` in a transformer and expecting a multisigmoidal last layer:
```python
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names, multilabel=True)
```

I am finding that when I perform `predict_proba`, every output is suming up to 1.0

```python
predictor = ktrain.get_predictor(learner.model, preproc=t)
predictor.predict_proba("hi i like football and religion").sum()
```

The output is always 1.0!

I am missing something or there is any kind of normalization being applied to the raw multisigmoidal last layer?

Regards.

**Comment by amaiya** [comment]
@Guillermogsjc  : Thanks for your comments and letting me know about this.

A while ago, the code was refactored with `multilabel` being set automatically in *ktrain* within `preprocess_train` by inspecting your data using a large sample. As a result, the `multilabel` parameter is currently ignored and this needs to change.  Either the `multilabel` argument should be removed or the explicit setting of `multilabel` provided by user should take precedence over what the data suggests.  I will change this.

**That said, the fact that the probabilities sum to 1 suggests that *ktrain* has inspected your data and determined that the labels are mutually-exclusive (i.e., not a multilabel problem).    What do your labels look like?  Do most examples in your dataset have mutually-exclusive labels?**  This might be why probabilities are summing to 1. 

For example, the following will print `True`, despite `multilabel` not being explicitly set because the labels are not mutually-exclusive (i.e., it is a multilabel problem):

```python
# multilabel problem
# first label element is positive/negative sentiment 
# second element indicates books vs. movies
x_train = ['i absolutely adore reading books.',
            'i really love books',
           'i hate movies',
            'i love movies',
            'i despise books.']
y_train = [[1, 1],[1, 1], [0, 0], [1, 0], [0, 1]]
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
print(t.multilabel) # prints True
```

Similarly, the following will print `False` because the labels **are** mutually-exclusive (**not** a multilabel problem):
```python
# non-multilabel problem
# first label element is for positive sentiment and second element is negative 
x_train = ['i absolutely adore reading books.',
            'i really love books',
           'i hate movies',
            'i love movies',
            'i despise books.']
y_train = [[1, 0],[1, 0], [0, 1], [1, 0], [0, 1]]
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
print(t.multilabel) # prints False
```

**Comment by Guillermogsjc** [comment]
Hi @amaiya,

thanks for the quick response.

Yes, despite putting it in a one-hot encoding fashion and setting `multilabel=True`, the example I putted is not based on mutually exclusive labels. 

So I understand that you have an automatic detection of exclusion between categories and it changes automatically to softmax.

It would be nice to have this as a warning or a behaviour when `multilabel=None`, but override this detection with the argument when it is `True`or `False`, putting a log about mutually exclusive if the  argument is `True` so it works as an advice (just a little suggestion).

Thanks again
Regards.

**Comment by amaiya** [comment]
OK - thanks.  I will leave this issue open, so as to make a change similar to what you suggested.

**Comment by amaiya** [comment]
In v0.15.3 of *ktrain*, the `multilabel` argument has been moved to the `Transformer.get_classifier` method and now correctly allows users to forcibly configure the model for multilabel classification regardless of what the data suggests.  It is recommended, though, to leave this value as `None` and allow *ktrain* to configure model based on observing the data.  Thanks for opening issue.
