### ISSUE TITLE
TypeError: can't pickle Tagger objects

### ISSUE THREAD

**Issue by mochan-tk** [amaiya/ktrain#159]
Hi
I am using
Amazon SageMaker
Ktrain version : 0.16.0
Model: cl-tohoku/bert-base-japanese-whole-word-masking
then try the sample on [example notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/MRPC-BERT.ipynb)
I always get this error:
![image](https://user-images.githubusercontent.com/9846618/83842227-5dfe1e00-a73d-11ea-9605-80078aeba0c0.png)

help really appreciate it.
Thank you.

**Comment by amaiya** [comment]
Hi,

The problem is related to the [MeCab package](https://pypi.org/project/mecab-python3/) used by `bert-base-japanese-whole-word-masking`.  MeCab objects (e.g., ` self.mecab = MeCab.Tagger()`) are not pickable for some reason, which causes problems with pickling the tokenizer.

However, for `transformer` models, the tokenizer does not need to be saved when `Predictors` are  saved as it can just be re-created on demand.  

I've pushed an update in v0.16.1, which should resolve the issue.  Please upgrade *ktrain* to v0.16.1 and try again and it should hopefully work correctly.  I just tested saving a `predictor` that uses  `bert-base-japanese-whole-word-masking` model and it now works for me.

**Comment by mochan-tk** [comment]
Thank you so much!
