### ISSUE TITLE
[QUESTION] Is there a way to use pre-trained models without internet?

### ISSUE THREAD

**Issue by stefanievonk** [amaiya/ktrain#164]
After training a model, one can copy this model to a different machine. To run it there with ktrain.load_predictor(filepath), ktrain seems to be downloading model files from the internet to a .cache folder in the user folder. Is there a way to prevent this and run the model without having to connect to the internet?

**Comment by amaiya** [comment]
[Transformers](https://github.com/huggingface/transformers)-based pretrained models are downloaded to `<home_directory>/.cache/torch/transformers`. For instance, on Linux, this will be `/home/<user_name>/.cache/torch/transformers`.   On Windows, this might be `C:\\Users\<user_name\.cache\torch\transformers`.

To reload the *ktrain* `predictor` on a machine with no internet access (for `ktrain` models that utilize models from `transformers` library), you'll need copy files from that folder to the same location on the new machine with no internet connection.

**Comment by stefanievonk** [comment]
And if I have downloaded multiple models, do you know how to distinguish between the different files (i.e. how do I know which files belong to which model, to which language)?

Thanks in advance

**Comment by amaiya** [comment]
One way is to simply clear the cache (remove or move all files out of the directory) and re-run the data-loading and model-creation steps, so that they are downloaded again. There's probably a better way, though, if you peruse the `transformers` library source to figure out where it determines if a model has already been downloaded.
