### ISSUE TITLE
distilbert: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#176]
While running this code
```
(X_train, y_train), (X_test, y_test), preprocess = text.texts_from_df(train_df = data_train,
                   text_column = 'Reviews',
                   label_columns = 'Sentiment',
                   val_df = data_test,
                   maxlen = 400,
                   preprocess_mode = 'distilbert')
```

I am getting this error.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-7ce8f21e2bb5> in <module>()
      4                    val_df = data_test,
      5                    maxlen = 400,
----> 6                    preprocess_mode = 'distilbert')

ValueError: too many values to unpack (expected 2)
```

However, this code is running okay.
```
(trn, val, preproc) = text.texts_from_df(train_df = data_train,
                   text_column = 'Reviews',
                   label_columns = 'Sentiment',
                   val_df = data_test,
                   maxlen = 400,
                   preprocess_mode = 'distilbert')
```

If I use `bert` then it is working in both cases. Not sure what is wrong here.

**Comment by amaiya** [comment]
DistilBert  [returns `TransformerDataset` instances, not arrays](https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb). Please change to this;:

```python
trn, val, preproc = text.texts_from_df(train_df = data_train,
                   text_column = 'Reviews',
                   label_columns = 'Sentiment',
                   val_df = data_test,
                   maxlen = 400,
                   preprocess_mode = 'distilbert')
```
When using `preprocess_mode='bert'`, it currently returns arrays as it currently uses `'keras_bert` package instead of `transformers` package.  On the other hand, `preprocess_mode='distilbert'` uses the `transformers` library and returns `TransformerDataset` instances. So, this explains the different behavior. This may change in the future due to the confusion it sometimes causes. But, for right now, BERT and DistilBert use different libraries.   If you look at the example notebooks, the different return values are shown.
