### ISSUE TITLE
[Question] Potential Integration with Run:AI's Optimizer

### ISSUE THREAD

**Issue by NicoleJaneway** [amaiya/ktrain#180]
Any potential for a future integration with [this package](https://github.com/run-ai/runai/tree/master/examples/ga), which enables gradient accumulation?  When I attempt to use the runai optimizer with ktrain:

`optimizer = runai.ga.keras.optimizers.Adam(steps=2)
model = t.get_classifier()
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'] )`

I get the following error:
> ValueError: ('Could not interpret optimizer identifier:', <runai.ga.keras.optimizers.Adam object at 0x15bb6add0>)

Thank you

**Comment by amaiya** [comment]
I think the reason it doesn't work is probably because it was designed for **standalone** Keras not `tf.keras`. *ktrain* now uses `tf.keras` and you can't mix Keras and tf.Keras. Since **stand-alone** Keras is no longer being updated, the `run:ai` project should probably migrate to `tf.keras`.   It should be an easy change to convert it to `tf.keras`, as it may just involve changing the imports.  You can try this yourself and see if it works,

**Comment by NicoleJaneway** [comment]
Per this [issue](https://github.com/run-ai/runai/issues/20), it doesn't look like something the Run:AI team is going to move forward to support.
