### ISSUE TITLE
I want to run ktrain zero shot learning on GPU but time latency is very high

### ISSUE THREAD

**Issue by SarangShaikh201** [amaiya/ktrain#194]
Hello I want to run the zero shot learning example from ktrain on gpu because on cpu it is taking 30 seconds to process classification for 840 categories. I was looking to parallelize this ktrain module so that i can run it with the GPU.
I have GeForce 1660 Ti (GB VRAM) GPU on my ubuntu 

Really needed the help.

Regards

**Comment by amaiya** [comment]
Thanks for letting me know about this.  

`ZeroShotClassifier` is implemented using a Natural Language Inference model that makes a prediction for each topic in `topic_strings`.  Thus, the prediction time increases with the number of categories.  The reason it was taking 30 seconds for 840 categories is because the `batch_size` was defaulting to 1.   **The solution is to increase the `batch_size`.**  

In v0.18.3 of *ktrain*, we have added a `batch_size` parameter to `ZeroShotClassifier.predict`.   We've set the default `batch_size` conservatively at 8, which reduces the prediction time from 30 seconds to roughly 4 seconds on a Titan V GPU.  If you increase the `batch_size` to 64, the prediction time reduces to ~1.5 seconds for 800 categories.

**Please upgrade *ktrain* to v0.18.3 and play around with the `batch_size` to drastically reduce prediction time.**
