### ISSUE TITLE
Ktrain based text classifier (internet off) - Two problems

### ISSUE THREAD

**Issue by sridhar-rv** [amaiya/ktrain#197]
Hi,

Env details : 
Linux : CENTOS 7.5
Python 3.7
Installed tensorflow 2.1
ktrain 0.14.5
transformers 2.8

**Problem 1** 
We had built the model in DEV server and deployed the model in PROD for prediction. Noticed the following issues.

    The prediction script looks at cache directory for the OS USER who created the model in DEV env. Even if the DEV OS user doesn't exist in PROD....it is expecting the same user. I had to create the same OS user in PROD and then copied the CACHE contents from DEV to PROD  and grant access to contents to all others. Then prediction worked. Why this behavior ?

Problem 2

     Tried building model afresh in PROD (internet off). Got the following error.
OSError: Can't load weights for 'albert-base-v2'. Make sure that:
- 'albert-base-v2' is a correct model identifier listed on 'https://huggingface.co/models'

I can download the prebuilt model as said in FAQ.

Can you please let me know how can i reference the three files (h5,json and vocab) in the training phase. 

Here is the code I have

  t = text.Transformer(paramDict['modelName'], maxlen=25, class_names=dataList[4])
  trn = t.preprocess_train(dataList[0], dataList[2])
  val = t.preprocess_test(dataList[1], dataList[3])
  model = t.get_classifier()
  learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
  learner.fit_onecycle(8e-5, numEpochs)

  Thanks
Sridhar

**Comment by amaiya** [comment]
Hello,

Note that there is a long-standing bug in the `transformers` library that causes problems with loading files from cache when there is no internet connectivity.  It seems to affect TensorFlow rather than PyTorch.  This is why you're seeing the ERROR: `OSError: Can't load weights for 'albert-base-v2'.`.  Hopefully, they'll fix it soon.  **In the meantime,  the [steps in the FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) describe a workaround solution that avoids these errors.**

Please find details below:

**Problem 1:**
The path to the cache directory is constructed by the `transformers` library, not *ktrain*.  It is supposed to look at the cache folder of the current OS user, not the user on the development server.  I believe it uses this to do so:

```python
from torch.hub import _get_torch_home
print(_get_torch_home())
```
Not sure why the above would print the home directory of USER on dev machine, if that's what's happening.

 I have never experienced the problem you're describing.   I will say that people train models on dev servers and Google Colab and apply these models on different machines all the time with no problem.  I did notice that you're using an older version of `transformers` and *ktrain*.   Perhaps, this is a bug in the version of `transformers` that you're using.  Have you tried upgrading `transformers` (and also *ktrain*) to the latest version to see if the problem still occurs?  If not, please do so and let me know if the problem persists.  The current version of `transformers` is v3.0.2 and the current version of *ktrain* is 0.18.3.
I believe the path is constructed by the `transformers` library using:



**Problem 2:**
 I have [updated the FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) with more details what to do.  Basically, you download the three files to a folder (e.g., `my_model_files`), copy the folder to the machine with no public internet access, and replace `MODEL_NAME` with the path the folder:
```python
t = text.Transformer('my_model_files', maxlen=25, class_names=dataList[4])
trn = t.preprocess_train(dataList[0], dataList[2])
val = t.preprocess_test(dataList[1], dataList[3])
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(8e-5, numEpochs)
```

**Comment by amaiya** [comment]
Also, when deploying a Hugging Face model using only a Predictor instance:
 ```pyton
p = ktrain.load_predictor('path_to_predictor_folder')
 p.predict(data)
```
... everything should work fine as long as the cache folder is populated correctly (i.e., vocab file is in the cache).  I just tested this on a machine with no internet connectivity and everything worked perfectly.
