### ISSUE TITLE
Add new layers on top of BERT but ktrain gives error when trying to fit the model

### ISSUE THREAD

**Issue by tjyh** [amaiya/ktrain#198]
Hi, 
Firstly, thanks for the amazing ktrain. 
I tried to add some new layers on top of BERT, but it gave me an error. Could you help me find out how to solve it? Thanks!

Specifically, It is a sentence-pair four-class problem. 
1) I used ktrain to preprocess my text data:
![image](https://user-images.githubusercontent.com/17846336/87348205-455b0200-c54c-11ea-8f8e-00b499f53276.png)

2) Then, I used transformers and keras to build the model, adding some layers on top of BERT:
![image](https://user-images.githubusercontent.com/17846336/87348302-691e4800-c54c-11ea-9f01-277a4ab3e84a.png)

3) Then, I tried to use ktrain to fit the model, but it gave an error:
![image](https://user-images.githubusercontent.com/17846336/87348425-99fe7d00-c54c-11ea-97dc-bec5c72fcf38.png)

**Comment by amaiya** [comment]
Hello:

The problem is with your Input layer, I think.    See this notebook for examples:

[https://github.com/cerlymarco/MEDIUM_NoteBook/blob/master/Siamese_Dual_BERT/Siamese_Dual_BERT.ipynb](https://github.com/cerlymarco/MEDIUM_NoteBook/blob/master/Siamese_Dual_BERT/Siamese_Dual_BERT.ipynb)


Also, `TFBertForSequenceClassification` already has a Dense layer on top of TFBertModel.
