### ISSUE TITLE
How to use index_from_folder for Question and Answer

### ISSUE THREAD

**Issue by msamwelmollel** [amaiya/ktrain#203]
Hi Amaiya 

I am doing Question and Anwer modelling. So I have split pdf file and have them stored in the same folder call train. I upload the folder to kaggle and then type text.SimpleQA.index_from_folder('/kaggle/input/train', INDEXDIR, commit_every=78). I think in this step is where I miss something since once I run the code and tries to prediction the answer by type following code answers = qa.ask('basic tutorials on some of the most?') qa.display_answers(answers[:5]). I receive the error says ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-7f810cbfd468> in <module>
----> 1 answers = qa.ask('basic tutorials on some of the most?')
      2 qa.display_answers(answers[:5])

/opt/conda/lib/python3.7/site-packages/ktrain/text/qa/core.py in ask(self, question, n_docs_considered, n_answers, rerank_threshold)
    311         # transform confidence scores
    312         confidences = [a['confidence'] for a in answers]
--> 313         max_conf = max(confidences)
    314         total = 0.0
    315         exp_scores = []

ValueError: max() arg is an empty sequence

Please could you share with us notebook which uses train data as pdf file stored in the folder?

Thank you.

**Comment by amaiya** [comment]
As indicated in the tutorial, the folder needs to contain **plain text** documents (i.e., `.txt` files that can be opened in NotePad).  The `index_from_folder` method  will skip over PDFs.  You're probably getting this error because your search index is empty.  If you want to index other files (Word documents, PowerPoint, PDFs), you'll need to convert them to text files yourself using a tool like [TIKA](https://tika.apache.org/index.html).

That said, if your folder contains only PDFs, you can use `ktrain.text.textutils.extract_copy` to create a new folder with `.txt` versions of each PDF in the folder. You will need `pdftotext` installed on your system.  Then, you would point `index_from_folder` to that folder created by `ktrain.text.textutils.extract_copy`.

As mentioned above, the reason you're getting an error is because the search for documents that match the question is returning no results (probably because your search index is empty).  I've made an update to *ktrain* that will handle this in a more graceful and informative manner. It is included v018.4.
