### ISSUE TITLE
Training with TPU

### ISSUE THREAD

**Issue by ericluo04** [amaiya/ktrain#212]
Hello - hope all is well! I've been experimenting with training using TPU (in colab) and came across a few errors. Would greatly appreciate any kind of guidance! 

When I set up a keras sequential model as below,
```
# handles if using TPU
if tpu:
    with tpu_strategy.scope():
        modelCNN = createCNN()
```
**ktrain.get_learner()** produces the following warning:  
`/usr/local/lib/python3.6/dist-packages/ktrain/core.py:41: UserWarning: Could not save original model weights warnings.warn('Could not save original model weights'). `
This error doesn't seem to be too crucial, since I can still fit the model (using TPU) and create/save a predictor. 

For posterity, using TPU still works with some models using ktrain wrappers (e.g. fastText below)
```
with tpu_strategy.scope():
    modelFT = text.text_classifier('fasttext', train, preproc = preproc)
```
However, TPU fails with distilled BERT:
```
    # load model
    t = text.Transformer("distilbert-base-uncased", 
                         maxlen = max_words, 
                         class_names = class_names)
    # pre-process (word embeddings and positional embeddings)
    train = t.preprocess_train(list(x_train), 
                               list(y_train))
    validation = t.preprocess_test(list(x_test), 
                                   list(y_test))
    # build model and learner
    with tpu_strategy.scope():
        model = t.get_classifier()
```
and produces this error:
```
No registered 'PyFunc' OpKernel for 'CPU' devices compatible with node {{node PyFunc}}
	.  Registered:  <no registered kernels>

	 [[PyFunc]]
```

**learner.lr_find()** produces the following error (and no mock training occurs): 
`File system scheme '[local]' not implemented (file: '/tmp/tmpadj535uy_temp_6668983f165b440cac3a4c90b1fa6784/part-00000-of-00002') Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors. [Op:Identity]`

**learner.fit()** produces the following error: 
`The number of samples 252544 is not divisible by batch size 1024. `
Perhaps include an option for steps_per_epoch in ktrain.get_learner? 

I also strongly suspect that **predictor.predict_proba()** isn't making use of TPU, since it takes a significantly longer time to predict than to train (e.g. validation with learner.fit happens almost instantly, whereas predicting on new data takes quite some time). I imagine this happens because even though modelCNN is ready for TPU, once you create the predictor variable (as in below), the predictor variable itself loses TPU access. 
`predictor = ktrain.get_predictor(learner.model, preproc=preproc) `

**Comment by amaiya** [comment]
Hello:

I don't currently use TPUs very much, but here are some answers that I hope help:

**`predictor.predict_proba` on TPU:**
As for running `predictor.predict_proba` on TPU, you may be right. However, if you're running predictions on TPU instead of GPU/CPU, you might want to just use the `tf.keras` API (or `transformers` API) directly by loading the model yourself in a way that supports TPU and executing predict on the model directly: e.g., `learner.model.predict` or `predictor.model.predict` or just `model.predict` if you load the model directly with `tf.Keras`.   The `Preprocessor` instance can still be used to preprocess te data into the format expected by the model.

**Problems with `ktrain.get_learner` and `learner.lr_find:`**
The error with `learner.lr_find` and the warning with `ktrain.get_learner` may be because both of these methods/functions save either the model or the model weights in a `/tmp` folder (because `tempfile` module is used).  This is [problematic for TPU training](https://github.com/tensorflow/models/issues/8265).   I suppose one solution is allow user to specify an alternative "temp" folder that resides in GCS bucket - perhaps as an environment variable that can be read by *ktrain*.

**number of samples not divisible by batch size**
The steps per epoch is actually calculated within *ktrain*.  The problem here may be a TensorFlow 2.1 issue.
See these TF 2.1 TPU issues like the problem with [number of samples not being divisible by batch size](https://github.com/tensorflow/tensorflow/issues/36718).

**DistilBert on TPU**
Not 100% sure, but one reason that DistilBert fails on TPU may be because it uses `tf.data.Dataset.from_generator`, according to [this stackoverflow post](https://stackoverflow.com/questions/60801403/notfounderror-no-registered-pyfunc-opkernel-for-cpu-devices-compatible-with),  There are recently-updated TF2 TPU examples in the `transformers` repo, so you can check there to see what steps they take to avoid these problems.  According to [this open TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/32712), the recommended solution is to use `TFRecords`.

**Comment by ericluo04** [comment]
Thanks a bunch amaiya - this was all very helpful! 

A little off-topic but ktrain is an awesome package that has really democratized SOTA machine learning. A year ago, I never would have imagined I could have jumped right into using BERT but here we are! Thanks again for your excellent work! 👍

**Comment by amaiya** [comment]
Thanks for your comments - very glad you've found it to be helpful!
