### ISSUE TITLE
Tensorflow 2.1 "MemoryError" during Ktrain installation on Ubuntu instance of AWS EC2

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#229]
Hello,

I was trying to deploy a model trained using Ktrain on AWS EC2 instance having Ubuntu 16.04.6 (Xenial Xerus) version. Following your advice from an [earlier issue](https://github.com/amaiya/ktrain/issues/177), I updated to pip3. Python3 is also installed.

Although, the independent installation of  **pip3 install tensorflow** is working fine, the installation of Ktrain using **pip3 install ktrain** is giving _**MemoryError**_ when Ktrain starts installing the dependency of tensorflow (2.1.0)

![image](https://user-images.githubusercontent.com/42617598/90306842-9dd84300-deee-11ea-8cca-873f287fd36a.png)

MemoryError at the end:

![image](https://user-images.githubusercontent.com/42617598/90306847-af214f80-deee-11ea-9140-36f0457e7383.png)

I would be grateful if you could inspect and kindly advise. Thanks.

**Comment by amaiya** [comment]
This is more of a pip issue rather than a *ktrain* issue.  If you google it, there are solutions [here](https://stackoverflow.com/questions/44335087/unable-to-install-tensorflow-memoryerror), [here](https://github.com/bjoernkarmann/project_alias/issues/14), and [here](https://chirale.org/2017/01/15/memory-error-on-pip-install-solved/), which all point to the same solution:

```
pip install --no-cache-dir packagename 
```
