### ISSUE TITLE
'stellargraph' should be included in the list of dependencies

### ISSUE THREAD

**Issue by tejashah88** [amaiya/ktrain#23]
I installed ktrain but when I tried to import it, it told me that 'stellargraph' was not found as a dependency. It should be added to the setup.py

**Comment by amaiya** [comment]
Thanks - this is now fixed.

Note that `stellargraph` was removed as a dependency in *ktrain* v0.5.1 because it seems to install tensorflow 1.14 (CPU), which disrupts existing tensorflow-gpu 1.14 installations.  The problem here is that there was a remaining reference to external `stellargraph` dependency that was accidentally not removed.  It was just removed/fixed in *ktrain* v0.5.2, so the error should no longer appear.

**Comment by tejashah88** [comment]
@amaiya Thanks for the quick fix!
