### ISSUE TITLE
Text Classification with Extra Features

### ISSUE THREAD

**Issue by inceatakan** [amaiya/ktrain#232]
Hello,

I am working on the LIAR dataset for fake news detection. When I try to add extra features on top of distilbert, as is done in https://github.com/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb,
I get the following error message:

AttributeError: Layer tf_distil_bert_for_sequence_classification_1 has no inbound nodes.

I use the same exact code in the link above. I have no idea how to fix the issue above.

Yours,
-Atakan Ince

**Comment by amaiya** [comment]
The tutorial employs the use of a vanilla `tf.keras` model.  The way you merge (or access intermediate layers) of a vanilla `tf.keras` model is different than the way you do the same with a `transformers` model.  It's on the TODO list to update the tutorial with this information and possibly an example using BERT or DistilBert, but I haven't had time yet.

Most of the tutorial notebook will remain the same.  But, if using a `transformers` model instead of the current model used, the approach would be to basically load the model as, say, a `DistilBertModel` and then merge the output with other features in a way similar to what is currently shown in the tutorial:
```python
    distilbert_model = TFDistilBertModel.from_pretrained('distilbert-base-uncased', config=config)
    embedding = distilbert_model(id_, attention_mask=mask_, token_type_ids=atn_)[0]
    # merge embedding outputs with output of other categorical/numerical features
```  
Feel free to respond and let me know if you have issues. Hopefully, I'll find time soon to provide an example notebook for this.

**Comment by amaiya** [comment]
Additional guidance is provided in [this issue](https://github.com/amaiya/ktrain/issues/252#issuecomment-696268468).
