### ISSUE TITLE
Reload the trained XLNET model from pytorch

### ISSUE THREAD

**Issue by aphuongle95** [amaiya/ktrain#256]
Hi, 

I have trained a XLNET classification model using my own dataset (tutorial: https://mccormickml.com/2019/09/19/XLNet-fine-tuning/) and now I want to load into ktrain for an explanation. 
I use this code to get some prediction, however, I got this error "AttributeError: 'TFXLNetForSequenceClassification' object has no attribute 'loss'". Do you have some ideas how this happens and how I could fix that?

Versions:
ktrain: 0.12.3
tensorflow: 2.1.9
torch: 1.4.0
transformers: 3.2.0

```from transformers import * 
m = TFAutoModelForSequenceClassification.from_pretrained(xlnet_out_address, from_pt=True)

# process with ktrain
MODEL_NAME = 'xlnet-base-cased'
t = text.Transformer(MODEL_NAME, maxlen=500, classes=[0,1])

# get predictor
predictor = ktrain.get_predictor(m, t)

# explain
predictor.predict(sentence)

**Comment by amaiya** [comment]
Hi,

I can look into this.  A couple of questions:  Is there a reason you're using v0.12.3 of ktrain, which is very old?  Is there a reason why you're training model in PyTorch instead of TensorFlow?

**Comment by aphuongle95** [comment]
> Hi,
> 
> I can look into this. A couple of questions: Is there a reason you're using v0.12.3 of ktrain, which is very old? Is there a reason why you're training model in PyTorch instead of TensorFlow?

Yes, sorry I have updated ktrain before posting, just did not rerun the code, now it is version 0.21.3. I used pytorch since it was the first version I got working. But it seems like it is not compatible with lime?

**Comment by amaiya** [comment]
After looking at your code again, I realized that you did not compile the model.  After invoking `from_pretrained`, try compiling your model with a loss function, optimizer, and metrics:
```python
m.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
```

Since, in some cases, certain things (e.g., language, class_names) in the `t` object are configured automatically by inspecting your data, I would also recommend running `t.preprocess_train` on a small sample of your training set for good measure before supplying `t` to `get_predictor`.

**Comment by aphuongle95** [comment]
yes, this has solved my problem. thank you very much! :)
