### ISSUE TITLE
Cannot import ktrain

### ISSUE THREAD

**Issue by YLi999** [amaiya/ktrain#262]
Hi, when I run "import ktrain", it gave the following warnings about GPU. I ignored the warning as it suggested. But then it kept running and did not return. Could you please provide any clues to this problem? The version of ktrain is 0.22.0, the version of python is 3.7.9, and the version of tensorflow is v2.3.1.

2020-10-08 16:30:18.768825: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-08 16:30:18.768859: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by amaiya** [comment]
Assuming you have a GPU, this sounds like a TensorFlow issue.  Did you setup CUDA for tensorflow and verified you can install tensorflow with no problem?

**Comment by YLi999** [comment]
> Assuming you have a GPU, this sounds like a TensorFlow issue. Did you setup CUDA for tensorflow and verified you can install tensorflow with no problem?

Thanks for the reply.

**Comment by YLi999** [comment]
> Assuming you have a GPU, this sounds like a TensorFlow issue. Did you setup CUDA for tensorflow and verified you can install tensorflow with no problem?

Thanks for the reply. But there is no GPU on the machine.

**Comment by amaiya** [comment]
Yes, the error says you can ignore it if there is no GPU.  

If you're wondering why something is stalling (e.g., training a model), then please post the exact code that is stalling so that I can try to reproduce.   It may be a resource issue on your end if you're trying to train a large model.

I am currently using **ktrain** v0.22.1 on a machine with only a CPU and am not experiencing any issues.
