### ISSUE TITLE
Available Models and Preprocessing

### ISSUE THREAD

**Issue by ericluo04** [amaiya/ktrain#280]
Hi amaiya! This package is really, really incredible - huge props. Though after working with ktrain for NLP, I have some suggestions/questions about clarity: 

1. What models are available in ktrain? I think [this](https://medium.com/@asmaiya/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed) is the last time you disclosed the full list of models, but several SOTA models have been released since then (e.g. Electra, T5, ERNIE). Are these included in ktrain? And could you please kindly include on the main github page a constantly updating list of available models? 

2. Can you clarify or link to an explanation of how each of the models pre-process data? Are you using huggingface or have you written your own code?

Thanks so much!

**Comment by amaiya** [comment]
Hello!  

I think you're asking about the `Transformer` API in **ktrain**, which is simply a wrapper for **text classification/regression** models in Hugging Face transformers.  As such, any model listed on the Hugging Face site is supported as long as there is a head for sequence classification. As shown in the blog post you linked to, you can look both [here](https://huggingface.co/transformers/pretrained_models.html) and on the [community-uploaded models](https://huggingface.co/models). For instance, I've never tried an Electra model, but it should now work  with the **ktrain**  `ktrain.text.Transformer` API since Hugging Face added a [TFElectraForSequenceClassification](https://huggingface.co/transformers/model_doc/electra.html#tfelectraforsequenceclassification) class.  

As far as pre-processing, we are just calling Hugging Face **transformers** methods for the most part. The library is open-source, so feel free to look through the source code for more details.  

Hope this helps!

**Comment by ericluo04** [comment]
Yes it does - that makes perfect sense. Thanks so much for your help!
