### ISSUE TITLE
Mlflow integration 

### ISSUE THREAD

**Issue by sanjaymeena** [amaiya/ktrain#284]
Hey Guys, has anyone tried integration of ktrain with mlflow ?

**Comment by amaiya** [comment]
Hello!  

I haven't used **mlflow** myself.  But, it seems straightforward to use with **ktrain**, since **ktrain** is just a lightweight wrapper:  e.g., all `*fit*` methods in `ktrain.Learner` can  accept callbacks and the underlying model is accessible via `learner.model`, etc. See [this video tutorial](https://www.youtube.com/watch?v=859OxXrt_TI&feature=youtu.be&t=840).
