### ISSUE TITLE
Transformers model metrics AUC instead of Accuracy

### ISSUE THREAD

**Issue by mattivi** [amaiya/ktrain#289]
I need to train a BERT classification model based on AUC and not on Accuracy as it is by default.
I took inspiration from this notebook https://github.com/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb and change the code as below, but I get an error.
How to do it in ktrain?

```python
t = text.Transformer(MODEL_NAME, maxlen=16, class_names=["0","1"])
model = t.get_classifier()

#here change the metric
metric_auc = tf.keras.metrics.AUC()
model.compile(loss="binary_crossentropy", optimizer='adam', metrics=[metric_auc])

model.summary()

learner = ktrain.get_learner(model, 
                             train_data=train_data, 
                             batch_size=32)

learner.fit_onecycle(1e-5, 2)
```

Then I get the error
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (tf_bert_for_sequence_classification_2/classifier/BiasAdd:0) = ] [[-0.312276721 -0.263820112][0.235869333...]...] [y (Cast_4/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_1/Assert}}]]
	 [[gradient_tape/tf_bert_for_sequence_classification_2/bert/embeddings/token_type_embeddings/embedding_lookup/Reshape/_582]]
  (1) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (tf_bert_for_sequence_classification_2/classifier/BiasAdd:0) = ] [[-0.312276721 -0.263820112][0.235869333...]...] [y (Cast_4/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_1/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_119045]

Function call stack:
train_function -> train_function
```

**Comment by amaiya** [comment]
Hello,

As a lightweight wrapper to `tf.keras`, things in **ktrain**  work in mostly the same way as TensorFlow Keras.  The cause of the problem here is that Hugging Face **transformers** models return logits instead of probabilities.  The error you're getting is because the `tf.keras.metrics.AUC` function is expecting probabilities.     Thus, the problem would also occur if using `tf.keras` directly.

You can double-check this, but it doesn't look like TensorFlow supports `from_logits` with metrics (only with  loss functions).  So, the solution to this is to probably implement your own AUC metric that runs output through softmax prior to computing AUC (similar to what was done [in this post](https://stackoverflow.com/questions/63580476/how-to-compute-auc-for-one-class-in-multi-class-classification-in-keras)) or you can compute it in a callback as was shown in [this FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-custom-metrics-with-ktrain) and do the same transformation.

If using the former approach, note that the `get_classifier` method accepts a `metrics` argument (i.e., a list of metrics).  So, you don't necessarily need to recompile the model:

```python
model = t.get_classifier( metrics=[MyCustomAUC(from_logits=True)] )
```

**Comment by mattivi** [comment]
Very clear, thanks for the explanations!
