### ISSUE TITLE
problem loading LM model trained with huggingface

### ISSUE THREAD

**Issue by srulikbd** [amaiya/ktrain#295]
hey.
I'm using ktrain for classification.
I tried fine tuning LM with HF, and then use the model with ktrain wonderful package..

I trained using the trainer api

and then trying loading the model using:

`t = text.Transformer(MODEL_LOCAL_PATH, maxlen=50, class_names=class_names)`

>  (is that the correct way?)
> 
> but the following message occured:
> 
> `preprocessing train...
> language: en
> train sequence lengths:
> 	mean : 27
> 	95percentile : 49
> 	99percentile : 57
> C:\Users\use

> 
> r\PycharmProjects\Deep_Learning\lib\site-packages\ktrain\utils.py:588: UserWarning: class_names argument was ignored, as they were extracted from string labels in dataset
>   if self.get_classes(): warnings.warn('class_names argument was ignored, as they were extracted from string labels in dataset')
> Traceback (most recent call last):
>   File "C:/Users/user/Google Drive/GitHub/Deep_Learning/Ktrain-BERT/Ktrain.py", line 562, in <module>
>     standard_classification_pipeline(df, df_test)#[:100])
>   File "C:/Users/user/Google Drive/GitHub/Deep_Learning/Ktrain-BERT/Ktrain.py", line 537, in standard_classification_pipeline
>     trn = t.preprocess_train(x_train, y_train)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\ktrain\text\preprocessor.py", line 1132, in preprocess_train
>     tseq = super().preprocess_train(texts, y=y, mode=mode, verbose=verbose)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\ktrain\text\preprocessor.py", line 902, in preprocess_train
>     tok, _ = self.get_preprocessor()
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\ktrain\text\preprocessor.py", line 855, in get_preprocessor
>     return (self.get_tokenizer(), self.tok_dct)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\ktrain\text\preprocessor.py", line 836, in get_tokenizer
>     self.tok = self.tokenizer_type.from_pretrained(model_name)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\transformers\tokenization_auto.py", line 220, in from_pretrained
>     return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\transformers\tokenization_utils_base.py", line 1425, in from_pretrained
>     return cls._from_pretrained(*inputs, **kwargs)
>   File "C:\Users\user\PycharmProjects\Deep_Learning\lib\site-packages\transformers\tokenization_utils_base.py", line 1531, in _from_pretrained
>     list(cls.vocab_files_names.values()),
> OSError: Model name 'C:\Users\user\Heavy Files\roberta-base-ft-as-en\checkpoint-80000' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'C:\Users\user\Heavy Files\roberta-base-ft-as-en\checkpoint-80000' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
> 
> Process finished with exit code 1

the roberta fine tuned directory containing the following files:
config.json
optimizer.pt
pytorch_model.bin
scheduler.pt
training_args.bin

I'm using the packages
ktrain==0.23.1
transformers==3.1.0
TF==2.1.0

tried both on windows 10 and on ubuntu 18.04

thanks a lot!

**Comment by amaiya** [comment]
Hi,

The error says you're missing `vocab.json`.  When you load a model locally using `Transformer`, it attempts to load the **tokenizer** from the supplied path, as well.  So, there are two approaches to that you can take.

### Approach 1 
You need to copy tokenizer files (which are very small) to that path.    This is also required when loading models without an internet connection, I think, as described in [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection).

Note that, when you save the `Predictor` to a folder,  you'll again need to make sure that folder  has the tokenizer files.  Otherwise, `predictor.predict` will yield the same error.


### Approach 2 
Alternatively, you could try loading the tokenizer yourself with **transformers** and  manually setting the `t.tok=tokenizer` prior to calling `preprocess_train`:

```python
t = text.Transformer(MODEL_LOCAL_PATH, maxlen=50, class_names=class_names)
from transformers import *
tokenizer = AutoTokenizer.from_pretrained('roberta-base')
t.tok = tokenizer
t.preprocess_train(...
```
When loading a predictor, you'll also need to reset tokenizer manually:
```python
p = ktrain.load_predictor('/tmp/mypred')
p.preproc.tok = tokenizer
p.predict('Some text to predict')
```

Hope this helps.

**Comment by srulikbd** [comment]
Thanks!!🌈
