### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by pradeepdev-1995** [amaiya/ktrain#307]
QA module showing ValueError: max()  in Question answering time.
Here is my code

from ktrain import text
INDEXDIR = '/tmp/myindex3'
text.SimpleQA.initialize_index(INDEXDIR)
text.SimpleQA.index_from_list(docList, INDEXDIR, commit_every=len(docList))
qa = text.SimpleQA(INDEXDIR)
answers = qa.ask(query)

But it showing the error

  File "/usr/local/lib/python3.6/dist-packages/ktrain/text/qa/core.py", line 291, in ask
    max_conf = max(confidences)
ValueError: max() arg is an empty sequence

**Comment by amaiya** [comment]
It looks like there are 0 viable answers being returned for whatever question you're running on whatever your dataset of interest is.   I've never encountered this, so I can't reproduce without access to your dataset and question.  But, under these circumstances, `ask` should probably return an empty list instead of raising the error you're seeing.  I'll mark this as a bug and fix it.  Thanks.

**Comment by pradeepdev-1995** [comment]
Thank you. Waiting for the updates

**Comment by amaiya** [comment]
Released in 0.25.4.  Thanks.

**Comment by pradeepdev-1995** [comment]
Thank you
