### ISSUE TITLE
load and save a model from saved checkpoint

### ISSUE THREAD

**Issue by Liranbz** [amaiya/ktrain#309]
Hi,
I try to create a model from a a saved checkpoint (for example: `weights-03.hdf5`).
my task is NLP, and I use text.classifier 
here is my code:

```
with open(args.pickle_folder + args.pickle_filename, 'rb') as f:
       (x_train,  y_train), (x_test, y_test), preproc = pickle.load(f)

model = text.text_classifier("bert", train_data=(x_train, y_train), preproc=preproc)
model.load_weights("ktrain/model_1/weights-03.hdf5")
learner = ktrain.get_learner(model, train_data=(x_train, y_train), batch_size=args.batch_size)

predictor = ktrain.get_predictor(model, preproc)
predictor.save(ktrain/model_1/)
```
I looked on FAQ but I didnt find the solution there
my questions are:
1. can you suggest an easier\clean way to create and save a model?
2. can I avoid loading the preproc and dataset?
3. can I use only the checkpoint file in order to create and save a model ? 
Thank you

**Comment by amaiya** [comment]
Hello,

See [this FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint). 

The recommended way to save/reload is to use `Predictor` instances, as shown in the example/tutorial notebooks:
```python
predictor = ktrain.get_predictor(model, preproc)
predictor.save('/tmp/mypred')
p = ktrain.load_predictor('/tmp/mypred')
```

Also, you have direct access to the model with `learner.model` and `predictor.model`. So, you can save/load models/weights/checkpoints however you would normally do it with `tf.keras`, `transformers`, `keras_bert`, etc. (without even using **ktrain**).  For instance, you can use `tf.keras` methods  `model.save_weights` and `model.load_weights`.  However, if you want to use **ktrain** `Predictor` instances to make predictions, a `preproc` object is required (but saving/reloading an entire dataset is NOT required).  

If you saved a checkpoint during the training process with the `checkpoint_folder` option in one of the `*fit*` methods and are asking how to reload it to make predictions,  the saved weights are intended to be used to reload during the training session (e.g., `learner.model.load_weights`) in case you overfit.  But, if the training session is finished and you remembered to save a Predictor, you can always do this:
```python
predictor = ktrain.load_predictor('/tmp/mypred')
predictor.model.load_weights('weights-03.hdf5')
```

Hope this helps.

**Comment by Liranbz** [comment]
Hi,
I use the **checkpoint_folder** option in the  **learner.fit_onecycle** method, so actually I get the weights after each epoch. In this case, I must keep the preproc in order to create a model for predictions.
Is it the only option, while using this method?
Thank you

**Comment by amaiya** [comment]
If by "this method", you mean using a `Predictor` instance to make predictions, then yes (because `Predictor` instances require a `preproc` object, as mentioned earlier).  However, you can make predictions yourself by using the `tf.keras` model directly 
 in which case you must preprocess the data yourself (which is fairly easy with `transformer` models like DistilBert).  If you're simply trying to make predictions in a way that requires a smaller footprint, you can convert the model to ONNX and make predictions without a `preproc` object and without **ktrain**, **TensorFlow**, or **PyTorch** even being installed as described in [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-make-quantized-predictions-with-transformers-models).
