### ISSUE TITLE
Need TF upgraded to 2.0

### ISSUE THREAD

**Issue by senthilmk** [amaiya/ktrain#32]
AttributeError: module 'tensorflow' has no attribute 'placeholder'

I am assuming this error because of being tied to TF < 2.0?

**Comment by HYC0311** [comment]
I have the same error while run text_classifier with TF=2.0.

**Comment by amaiya** [comment]
Tensorflow 2.0 will be supported soon at the same time we transition to tf.keras as default for ktrain.

As of right now, ktrain is locked to standalone Keras 2.2.4 and TF 1.14.

**Comment by amaiya** [comment]
*ktrain* v0.7.0 has been released and now uses `tf.keras` instead of Keras.  It can be used with TensorFlow 2.0, but TensorFlow 1.14 should still work also.

If using TensorFlow 2.0, *ktrain* presently runs in 1.x mode using `tf.compat.v1.disable_v2_behavior`. 
 In the future, this will be removed and only TensorFlow 2 will be supported.
