### ISSUE TITLE
Bert Tokenizer from ONNX Import

### ISSUE THREAD

**Issue by lucala** [amaiya/ktrain#321]
I'm exporting a Bert model using your ONNX exporter. I need to import the ONNX model in Java. The export and imports work but I need to access the tokenizer. It is unclear to me how I can retrieve this from the ONNX object.

Looking through the code I can see that input_dict is saved using `_set_save_spec` but I'm not sure how to retrieve it.

```
if U.is_huggingface(model=self.model):
     tokenizer = self.preproc.get_tokenizer()
     maxlen = self.preproc.maxlen
     input_dict = tokenizer('Name', return_tensors='tf',
                           padding='max_length', max_length=maxlen)

     if version.parse(tf.__version__) < version.parse('2.2'):
          raise Exception('export_model_to_tflite requires tensorflow>=2.2') <-- copy/paste typo? export_model_to_onnx?
          #self.model._set_inputs(input_spec, training=False) # for tf < 2.2
     self.model._saved_model_inputs_spec = None # for tf > 2.2
     self.model._set_save_spec(input_dict) # for tf > 2.2
     self.model._get_save_spec()

onnx_model = keras2onnx.convert_keras(self.model, self.model.name, target_opset=target_opset)
keras2onnx.save_model(onnx_model, fpath)
```

I'm also a bit confused by your tutorial notebook:
```
onnx_model_path = '/tmp/model.onnx'
onnx_model_path = predictor.export_model_to_onnx(onnx_model_path)
print(onnx_model_path)

# create ONNX inference session (you can also do this manually instead of using create_onnx_session)
sess = predictor.create_onnx_session(onnx_model_path)

# preprocess and predict outside of ktrain and TensorFlow
doc = 'I received a chest x-ray at the hospital.'
maxlen = predictor.preproc.maxlen
tokenizer = predictor.preproc.get_tokenizer()
input_dict = tokenizer(doc, max_length=maxlen, padding='max_length', truncation=True)
feed = {}
feed['input_ids'] = np.array(input_dict['input_ids']).astype('int32')[None,:]
feed['attention_mask'] = np.array(input_dict['attention_mask']).astype('int32')[None,:]
output_onnx = sess.run(None, feed)
```
Why are you using the same predictor which you just saved to ONNX to load in the model again? How would the import look like if you were starting from scatch, only with an ONNX file and no predictor?

**Comment by amaiya** [comment]
It may be more clear if you look at [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-make-quantized-predictions-with-transformers-models).   This FAQ entry shows the current recommended practices for ONNX deployments of `transformers` models such as converting from TensorFlow to PyTorch first before converting to ONNX and deploying **without** TensorFlow, PyTorch, or **ktrain** needing to be installed on the deployment server.  (The notebooks you referenced should probably be modified based on this FAQ entry, which we can do later.)

To your first question, in terms of tokenizing the input, this is typically done using `transformers` directly (which you can do in a lightweight way without having TensorFlow or PyTorch installed). The tokenizer is not saved as part of the ONNX model.  If you are using Java, then there is Java code to do the tokenization available in various places like [here](https://github.com/huggingface/tflite-android-transformers/tree/master/bert/src/main/java/co/huggingface/android_transformers/bertqa/tokenization).   If you have any trouble, you can deploy your ONNX model using ONNX runtime with Python for tokenization and serve the model using a REST API, which can be accessed by your Java application (or Node.js or PHP, etc.).

To your second question, if you're referring to the line: `predictor.create_onnx_session`, you'll see in the comments that it says you can manually create the onnx session without the predictor.   That convenience method was just used to make things more concise for illustration purposes since creating the ONNX session is boilerplate code. It should probably be replaced with the raw code to create the onnx session to avoid confusion, as mentioned above.  

Hope this helps.
