### ISSUE TITLE
Iteratively training models

### ISSUE THREAD

**Issue by harttraveller** [amaiya/ktrain#326]
Hi, thanks for maintaining this great library! I ran into a number of warnings while training models iteratively, and would appreciate some guidance. I have some code that goes through a dataset, constructs, and saves models to independent directories for later use. 

```
for col in findings:
    print(col)
    print()
    
    f,n,c = construct_datasets(data,col)
    
    # setting up directory
    os.mkdir('models/{}'.format('_'.join(col.lower().split())))
    
    # creating finding model
    os.mkdir('models/{}/findings'.format('_'.join(col.lower().split())))
    X = f['text'].tolist()
    y = f['labels'].tolist()
    t = text.Transformer(MODEL_NAME, maxlen=500, class_names=[0,1])
    trn = t.preprocess_train(X, y)
    model = t.get_classifier()
    learner = ktrain.get_learner(model, train_data=trn, batch_size=6)
    learner.fit_onecycle(8e-5, 2)
    predictor = ktrain.get_predictor(learner.model, preproc=t)
    predictor.save('models/{}/findings'.format('_'.join(col.lower().split())))
```

This works well up to around the 8th model, but after that point I start getting the following warning:

```
/usr/local/lib/python3.6/dist-packages/ktrain/core.py:41: UserWarning: Could not save original model weights
  warnings.warn('Could not save original model weights')
```

It seems to be in line 41 of this file:

https://github.com/amaiya/ktrain/blob/master/ktrain/core.py

I'm curious though if this is a warning I can ignore, or if the models saved are changed in some way or not saved properly due to the warning.

Also - I'd be curious whether or not the warning can be solved, perhaps it is due to a lack of memory in the GPU? I am not an expert at this so forgive if I am totally off the mark, but perhaps having the functionality to deallocate GPU memory after each training session would work? I am probably totally off the mark, but thought I would throw that idea out there.

For context, I am using a paperspace gradient instance, specifically their transformers + NLP environment. If there is any other information I could add, let me know and I will add it!

**Comment by amaiya** [comment]
Hello:

 That warning should probably be updated to print a reason why the original weights could not be saved.   I just updated the `develop` branch so that the warning will also show the error message from the exception which may or may not shed light on what's going on.  You can install the `develop` version with: 
```
pip install git+https://github.com/amaiya/ktrain@develop
```
If you need more information, you can manually try saving the weights at each iteration and see what the full traceback is.

That said, the original weights are only saved so that you can more easily reset the weights to what they were prior to starting training with `learner.reset_weights`. So, if everything else is working correctly, you can probably ignore it if you want.

Hope this helps.  I'll close this issue.  But, if you try viewing the error, feel free to respond to this thread to post what it was.
