### ISSUE TITLE
load_predictor issue when loading pre trained model on colab

### ISSUE THREAD

**Issue by DanieleMele** [amaiya/ktrain#341]
Hi 
I become an error when trying to import a pretrained model on colab:
It is caused by: raise Exception('Failed to load .preproc file in either the post v0.16.x loction (%s) or pre v0.16.x location (%s)' % (os.path.join(fpath, U.PREPROC_NAME), fpath+'.preproc'))

Can you help my out? Is this in relation with the pickle version?
Thanks
Regrads Daniele

**Comment by DanieleMele** [comment]
Hello 
Thank you for your answer. The .preproc file is in the folder. Maybe it helps if I post the whole error message:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ktrain/core.py in load_predictor(fpath, batch_size, custom_objects)
   1470         preproc_name = os.path.join(fpath, U.PREPROC_NAME)
-> 1471         with open(preproc_name, 'rb') as f: preproc = pickle.load(f)
   1472     except:

ModuleNotFoundError: No module named 'transformers.configuration_xlm'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
2 frames
FileNotFoundError: [Errno 2] No such file or directory: '/folder.preproc'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ktrain/core.py in load_predictor(fpath, batch_size, custom_objects)
   1476             with open(preproc_name, 'rb') as f: preproc = pickle.load(f)
   1477         except:
-> 1478             raise Exception('Failed to load .preproc file in either the post v0.16.x loction (%s) or pre v0.16.x location (%s)' % (os.path.join(fpath, U.PREPROC_NAME), fpath+'.preproc'))
   1479 
   1480     # load the model

Exception: Failed to load .preproc file in either the post v0.16.x loction (folder/tf_model.preproc) or pre v0.16.x location (folder.preproc)

**Comment by amaiya** [comment]
After looking at the entire error, I see now that the issue is indeed related to the new version of **transformers** and the "pickle" issue.  As mentioned [here](https://github.com/amaiya/ktrain#news-and-announcements), you will need to either edit the `.preproc` file so that module paths conform to the new version of **transformers** or re-generate the `.preproc` file.   

In the former case, you'll see this at the top of your error message:
```
ModuleNotFoundError: No module named 'transformers.configuration_xlm'
```

This is the main problem.  So, you'll need to change  `transformers.configuration_xlm` to `transformers.models.xlm.configuration_xlm`.   (If you look in the **transformers** installation directory, the `configuration_xlm.py` file is in a different folder than where it was in `transformers<4.0`, which is why the change is needed.)  There will at least two other things you'll need to change in the file, as well, as described in the link above.

**Comment by DanieleMele** [comment]
Ah ok I got it, yes now works, thank you very much
Regards
Daniele
