### ISSUE TITLE
failing to run at multi label problem and treating it as binary problem

### ISSUE THREAD

**Issue by mv96** [amaiya/ktrain#346]
(X_train,y_train),(X_test,y_test), preprocess = text.texts_from_df (train_df=data_train,
                                                                    text_column="texts",
                                                                    label_columns="label",
                                                                    val_df=data_test,
                                                                    maxlen=100,
                                                                    preprocess_mode="bert")

the label column contains multi class labels

getting this ==
Is Multi-Label? False 

print(len(np.unique(y_train))) gives me length of 2 when originally 3 labels in the column

**Comment by amaiya** [comment]
As demonstrated in the tutorial, multi-label problems require multiple columns that are many-hot-encoded:
```
    Loads text data from Pandas dataframe file. Class labels are assumed to be
    one of the following formats:
        1. one-hot-encoded or multi-hot-encoded arrays representing classes:
              Example with label_columns=['positive', 'negative'] and text_column='text':
                text|positive|negative
                I like this movie.|1|0
                I hated this movie.|0|1
            Classification will have a single one in each row: [[1,0,0], [0,1,0]]]
            Multi-label classification will have one more ones in each row: [[1,1,0], [0,1,1]]
        2. labels are in a single column of string or integer values representing class labels
               Example with label_columns=['label'] and text_column='text':
                 text|label
                 I like this movie.|positive
                 I hated this movie.|negative
       3. labels are a single column of numerical values for text regression
          NOTE: Must supply is_regression=True for integer labels to be treated as numerical targets
                 wine_description|wine_price
                 Exquisite wine!|100
                 Wine for budget shoppers|8

```


 You've only specified one column.   The returned `y_train` variable should be one-hot-encoded (binary or multi-classification) or multi-hot encoded (multilabel) where each column will only contain a 1 or 0.  



Note also that there is a difference between multi-label and having more than 2 classes (multiclassification).  Examples in multi-label problems can have multiple targets, whereas in multi-classification each example is assigned one of possibly many targets.  

 Please follow tutorial for more information.


P.S. If you switch to DistilBert (which returns objects instead of Numpy arrays), make sure you switch to something like this:
```
trn, val, preproc = text.texts_from_df(...
```

**Comment by mv96** [comment]
Hello Amaiya,

Sorry I was a bit confused  in the beginning my problem revolves around multi class but not multi label (like you mentioned), so I followed the tutorial ipynb and with the your comments, I was able to fix it easily. 

Like you said when printing the shape of Y_train I can see it has 3 columns now (what was be expected)

Thanks mate 👍
