### ISSUE TITLE
ERROR MESSAGE - TENSORFLOW NEEDS TO BE INSTALLED

### ISSUE THREAD

**Issue by salsa360** [amaiya/ktrain#349]
Hi Arun,

I am having difficulty in installing Ktrain on Windows 10.  When I try to run Ktrain in Jupyter notebook, I get an error message stating that Tensorflow needs to be installed - which I did install before installing Ktrain.  

Do you have any advice?  Thank you.

**Comment by amaiya** [comment]
Please follow these  installation steps for Windows:
https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-install-ktrain-on-a-windows-machine

The error basically means that **ktrain** tried to do `import tensorflow as tf` and it didn't work (i.e., TensorFlow was not installed correctly).

**Comment by salsa360** [comment]
Hi Arun,

I am following the installation steps and now ge the following error
message when I run "pip install tensorflow==2.3":

ERROR: Could not find a version that satisfies the requirement
tensorflow==2.3
ERROR: No matching distribution found for tensorflow==2.3

What do I do?


Thanks.

**Comment by amaiya** [comment]
Are you sure you are following the steps exactly as posted because it sounds like you forgot:

`pip install -U pip`

**Comment by salsa360** [comment]
Hi Arun,

Your comment "pip install --upgrade pip":
Requirement already satisfied: pip in
c:\users\kushwant\appdata\local\programs\python\python39\lib\site-packages
(21.0.1)

Finally able to install Tensorflow.

Now, the problem is with installing ktrain.  Getting the following error
message "
ERROR: Failed building wheel for tokenizers
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot
be installed directly

It keeps harking to upgrading pip but this is already done.

Thanks.

**Comment by amaiya** [comment]
Hi:  I just tested [these Windows installation instructions](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-install-ktrain-on-a-windows-machine) myself on Windows 10 and everything works.   

It doesn't look like you've followed the instructions correctly because your error says that you're using  non-conda Python 3.9 (instructions use Miniconda Python 3.7).  If you followed the directions exactly, then running the following commands on the Python prompt (or within Jupyter notebook) should print `C:\Users\kushwant\Miniconda3\envs\kt`.   

```python
import sys, os
print(os.path.dirname(sys.executable))
# prints C:\Users\kushwant\Miniconda3\envs\kt
```

In your case, it looks like you're using Python 3.9 installed in appdata somehow.  Perhaps, your Jupyter notebook is using Python 3.9 instead of the Minconda Python or something.  Regardless, this doesn't appear to be an issue with **ktrain**.

**Comment by salsa360** [comment]
Hi Arun,

Thanks for your input.  I've reinstalled ktrain using your
recommended guidelines but I am still having difficulty.  It appears to be
a clash between the ktrain and pycaret packages - see the extract below.

ERROR: pip's dependency resolver does not currently take into account all
the packages that are installed. This behaviour is the source of the
following dependency conflicts.
pycaret 2.3.0 requires numpy==1.19.5, but you have numpy 1.18.5 which is
incompatible.
phik 0.11.2 requires scipy>=1.5.2, but you have scipy 1.4.1 which is
incompatible.


Regards
Kushwant

**Comment by amaiya** [comment]
Again, these are not **ktrain** issues.  

Numpy  1.18.5 is being installed by TensorFlow 2.3.  You can probably get rid of this error message by upgrading TensorFlow.

I don't know anything about phik package.  

If you have dependency conflicts, you can create separate virtual environments.  

Again, these are not **ktrain** issues and are related to the basics of pip and Python.
