### ISSUE TITLE
Question/suggestion about document similarity

### ISSUE THREAD

**Issue by ilos-vigil** [amaiya/ktrain#359]
1. When we use NMF (rather than LDA), then train/build & call `score` function, can we still assume that ALL positive score means similar document and vice versa?
2. I find NMF performs much better than LDA on few cases, i think it's worth to mention it on [example notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/20newsgroups-document_similarity_scorer.ipynb).

**Comment by amaiya** [comment]
Hi:  NMF support was actually added as a PR by another user who also found it performed better on his particular dataset.

Regarding 1, the answer is "yes" because the `train_scorer` and `score` methods simply uses a 1-class classifier, so the numeric features employed by the classifier/scorer do not necessarily need to be LDA probabilities.

Regarding 2:  I have added a note about NMF in the `develop` branch.  Thanks for suggestion.
