### ISSUE TITLE
get_predictor().predict() returns class label name only

### ISSUE THREAD

**Issue by julianmukaj** [amaiya/ktrain#36]
On a trained BERT model, when I run code below:

Input: 
`predictor = ktrain.get_predictor(learner.model, preproc)`
 `predictor.predict(data_df["para"][0])`

Output:
`'target'`

This does not match up to documentation and examples shown, assuming this is an issue

**Comment by amaiya** [comment]
`TextPredictor.predict` is a convenience wrapper around the `model.predict` method in Keras.  It preprocesses the raw text into the form expected by the model and outputs the predicted class label by default.  This is consistent with the  tutorials and example notebooks.  See [this Google Colab notebook](https://colab.research.google.com/drive/1AH3fkKiEqBpVpO5ua00scp7zcHs5IDLK), for example.   If you see documentation or examples that show different, please reply with what you are looking at, so that it can be corrected.  

If you're trying to get the predicted class probabilities, you can either call `predictor.predict_proba` or supply `return_proba=True` to `predictor.predict`:
```
predictor.predict_proba(data_df["para"][0])
```

If the above doesn't address issue, then please reply and provide more details.
