### ISSUE TITLE
Offline Training with Transformers 

### ISSUE THREAD

**Issue by MocktaiLEngineer** [amaiya/ktrain#391]
I was following this [link](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) to do offline training and prediction for a text classification task. I downloaded the required 3 files (tf model, vocab and config) into a directory which I named as 'bert-base-uncased', but it wouldn't work because it told that the tokenizer files weren't found in the said directory, however, when I changed the directory name to 'base-uncased', it worked. This seems strange as to why it wouldn't work previously, but works after changing the directory name. 

I'd like to work on this issue, and do a PR if you're okay with it. Please confirm if this is a issue, thank you!

**Comment by amaiya** [comment]
Hello @MocktaiLEngineer 

Thank you for offering to contribute a PR for this issue - that would be great.

It is particularly appreciated, since I was not able to reproduce this problem on my end.  My testing environment was a Windows 10 laptop with a Mint 20 guest operating system (via  VirtualBox) with Python 3.8, transformers 4.3.3, TensorFlow 2.3.1, and ktrain v0.27.3.  I named the model folder `~/Downloads/dmodel` and had no problems with loading and training the model (including  saving and re-loading the precdictor) while internet access was disabled.   (Note also that I trained a `distilbert-base-uncased` model, not a `bert-base-uncased` model.)

So, I'd be very interested in learning what you discover as you explore this issue and resolve it.

Feel free to reply to this thread, if you have questions as you work on this.
