### ISSUE TITLE
Facing Issue in learner.lr_find()

### ISSUE THREAD

**Issue by aravinddeveloper** [amaiya/ktrain#396]
I am facing issue while calling learner.lr_find() method. attached snap for reference. 
Basically I am calling Distilbert model using TFAutomodel from Hugging face and I am adding FFN head at the end using keras for classification. Then I inported ktrain and fed the model into learner. The purpose I use ktrain here is to make use of Fit_onecycle() method.
![issue](https://user-images.githubusercontent.com/61618332/138602850-ce1466b8-d63d-4515-ae4b-4a03ef20bb99.PNG)

**Comment by aravinddeveloper** [comment]
>

**Comment by aravinddeveloper** [comment]
I have shared my code and error traceback thru below link. request you to go through
[code and error traceback.txt](https://github.com/amaiya/ktrain/files/7445737/code.and.error.traceback.txt)

**Comment by amaiya** [comment]
Thanks.  The problem is that you've constructed a vanilla Keras Sequential model with a `transformers`  as an individual layer. 
 The error is occurring because `save_model` (which is called only for vanilla Keras models) does not work with `transformers`.  A possible workaround is to supply `restore_weights_only=True` to `lr_find`.  Alternatively, you can use an instance of `TransformerTextClassLearner` and wrap your dataset in a `TransformerDataset`, which is what the built-in `transformers` models use what you've already confirmed works.
