### ISSUE TITLE
onnx export using tf2onnx

### ISSUE THREAD

**Issue by lucala** [amaiya/ktrain#399]
Hi, I'm trying to export a BERT huggingface ktrain predictor to ONNX. Your code uses keras2onnx which is not actively developed anymore and frozen to TF2.3. Apparently, tf2onnx is the way to go with a similar API with `tf2onnx.convert.from_keras()` replacing `keras2onnx.convert_keras()`.

Unfortunately, it doens't work out of the box. Running this modified code I get `TypeError: Invalid input_signature tf_bert_for_sequence_classification_1; input_signature must be a possibly nested sequence of TensorSpec objects.`.

Any idea on how to fix this? I'd rather not downgrade TF. Thanks.

(btw offtopic question: where do you get the info for the last part in FAQ where you state for what ktrain has been used?)

**Comment by amaiya** [comment]
Hello,

Have you seen this [FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-make-quantized-predictions-with-transformers-models)?

Since you're using a Hugging Face model, you can convert to Pytorch and then save to ONNX.  The last time I checked, there was an advantage to doing the intermediate PyTorch conversion. Many ktrain users have successfully deployed lighter-weight ONNX models this way.  No need to downgrade TF.

To your last question, they're from a combination of personal communications and academic citations to either the paper or GitHub repo.
