### ISSUE TITLE
Ktrain Bilstm-Bert using cased models , output entities in lowercase

### ISSUE THREAD

**Issue by dummynov1** [amaiya/ktrain#422]
I have been training a custom BioMedical NER model using 'Bi-lstm Bert' with SciBERT cased embeddings using:

`WV_URL='https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.nl.300.vec.gz'
model = txt.sequence_tagger('bilstm-bert', preproc, 
bert_model='allenai/scibert_scivocab_cased', wv_path_or_url=WV_URL)`

After training when i load the model into predictor()  to predict on data, all the entities extracted are returned in Lowercase. Is there any option i need to enable so that Case remains same as original text, even though i'm using a Cased pretrained model.?

**Comment by amaiya** [comment]
The problem doesn't seem to occur with other cased models, as can be seen in [this notebook](https://github.com/amaiya/ktrain/blob/master/examples/text/CoNLL2003-BiLSTM.ipynb).
The Sci-BERT CASED model doesn't seem to retain case in the same way for some reason.

```python
from transformers import  AutoTokenizer
model = 'bert-base-cased'
tokenizer = AutoTokenizer.from_pretrained(model)
print(tokenizer.tokenize('Hello')
# ['Hello']
```

```python
from transformers import  AutoTokenizer
model = 'allenai/scibert_scivocab_cased'
tokenizer = AutoTokenizer.from_pretrained(model)
print(tokenizer.tokenize('Hello')
# ['hel', '##lo']
```
According to [this issue](https://github.com/huggingface/transformers/issues/3823), it looks like this is because this model wasn't uploaded with the `tokenizer_config.json` specifying it shouldn't be lowercased.

A workaround is to do the following:
```python
from transformers import AutoTokenizer
preproc.p.te.tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_cased', do_lower_case=False)
```

**Comment by dummynov1** [comment]
Thanks for sharing the info on Scibert Cased model tokenizer config issue. 
Just to confirm should i use your workaround like this:

```
TDATA = 'train2.txt'
VDATA = 'test2.txt'
(trn, val, preproc) = text.entities_from_conll2003(TDATA, val_filepath=VDATA)

```

```
from transformers import AutoTokenizer
preproc.p.te.tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_cased', do_lower_case=False)
```

```
WV_URL = 'https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz'
model = text.sequence_tagger('bilstm-bert', preproc, 
                            bert_model='allenai/scibert_scivocab_cased', wv_path_or_url=WV_URL)
```

Is this how the Preproc tokennizer to be intialized, befor running learner code ?
