### ISSUE TITLE
Question : Ktrain Bilstm-Bert with SciBert NER model port to offline system?

### ISSUE THREAD

**Issue by dummynov1** [amaiya/ktrain#423]
I want to port a ktrain based custom trained Bilst-Bert with SciBert NER model on a system with no internet access (Restricted private network).
I read the FAQ section on how to use ktrain models offline  for Text Classification and QA (Couldn't find for NER).

My model is saved using `predictor.save('folder_path')`. I trained the Bilst-Bert with SciBert cased (bert-model) on small training data (250 datapoints) . So the model file (H5) was just 14mb and a vocab file (not sure why, since actual pre -trained SciBert model size is ~450mb)
While when i reload the model from 'folder_path' , it automatically loads both SciBert pretrained model(at cache/huggingface/ folder) along with my saved model. Why does it require  2 separate model files to be used together?
Is there a way if we can just get 1 single model, or combine both into a single model file?
Also, how do we port this model and embeddings to another system with no internet access

**Comment by amaiya** [comment]
Hello:  It requires two separate models because two separate models are used.  In `bilstm-bert`, a BERT `transformers` model is used to generate word embeddings that are fed to a BiLSTM model.

As far as porting to systems with no internet access, you should be able to use a similar scheme to the ones described for QA and text classification - replace model names with paths to folders containing the model files (don't forget the embedding model, as well).  If you encounter any issues, please reply to this issue, so we can address it.  Also, if you do encounter issues, you can also try manually loading and tweaking the model configuration as illustrated in [your other issue](https://github.com/amaiya/ktrain/issues/422). 
 Hope this helps.

**Comment by amaiya** [comment]
As of right now, the underlying `transformers` embedding model is loaded from the original model name supplied (e.g., `allenai/scibert_scivocab_cased`), which either requires an internet connection or requires the model files to exist in the `huggingface` cache folder on the offline machine.  If **transformers** is giving you trouble loading the model/tokenizer/configuration files from the cache on the offline machine, the following workaround works.  In addition to saving the predictor, you simply save all files related to the `transformers` model to the same folder, and reset the embedding model name to the folder, as well:

```python
predictor.preproc.p.te.model.save_pretrained('/tmp/offline')
predictor.preproc.p.te.tokenizer.save_pretrained('/tmp/offline')
predictor.preproc.p.te.config.save_pretrained('/tmp/offline')
predictor.preproc.p.te_model = '/tmp/offline'
predictor.save('/tmp/offline')
```
On the machine that is offline, you can then load the predictor without an internet connection:  `predictor = ktrain.load_predictor('/tmp/offline')`.   Once the predictor/model is successfully loaded on the offline machine, you can repeat the steps above to save the model to whatever location you want.

**Comment by amaiya** [comment]
A change has been pushed  to the `develop` branch that will automatically save the `transformers` embedding files and update the model name (`te_model`) to facilitate offline loading of NER models with transformers embeddings.

**Comment by amaiya** [comment]
This issue should now properly fixed in the `develop` branch, but is not tested/released yet.  If you save the predictor with `predictor.save('/tmp/mypredictor')`, it will automatically save both the NER model and the transformers embedding model. You can then move the `mypredictor` folder to a machine with no internet connectivity and re-load both the NER model and the embedding model with `predictor = ktrain.load_predictor('mypredictor')`.    This was tested using a `bert-base-cased` model.  Thanks.
