### ISSUE TITLE
Reuse of the trained model

### ISSUE THREAD

**Issue by terence92** [amaiya/ktrain#431]
Hi, I have trained a Distilbert model on my database. Now I would like to load it and use it to train on a similar database but with different number of classes.

How can I do? I have read this article

https://discuss.huggingface.co/t/how-do-i-change-the-classification-head-of-a-model/4720/20

The parameter ignore_mismatched_sizes = True can I set it using ktrain?

Thank you

**Comment by amaiya** [comment]
Since **ktrain** is just a thin wrapper, you can access the model directly and configure/manipulate as desired.  However, when making predictions, you'll probably want to preprocess the inputs and feed them directly to the model, as illustrated in the [ONNX notebook](https://nbviewer.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb).  This would be the easiest approach.

If using a `Predictor` instance to make predictions on the second database, you'll need to re-configure the `Preprocessor` instance based on the different number of labels.  It should be possible to do this, but you'll need to experiment with how to do it if you want to go this second route.
