### ISSUE TITLE
NER: Behaviour of 'I-' labels on single line entities

### ISSUE THREAD

**Issue by Niekvdplas** [amaiya/ktrain#442]
Hi, I've found an interesting thing while training a NER predictor on a dataset with both multi word entities as well as single word entities. Whenever a single word entity is split up in tokens, the tokens will get an 'I-' label appended from another class.

Here an example with a hypothetical dataset with two entities in it: 
`B-EMAIL, B-NAME, I-NAME`. 

Detecting names in entries is straightforward as the beginning token of the entity will have a 'B-' assigned while the rest are assigned an 'I-' as should be. The problem is when the model is introduced to an token that succeeds a beginning token in an Email (which in the conll formatted file would be always on one line thus only having `B-EMAIL`.

The email 'NiekusesKtrain@gmail.com' would then be tokenized and labelled as follows: 
```
('NiekusesKtrain', 'B-EMAIL'),
 ('@', 'I-NAME'),
 ('gmail', 'I-NAME'),
 ('.', 'I-NAME'),
 ('com', 'I-NAME')
```

A quick and dirty fix would be to look at the 'B-' tag and assign the tag it to all succeeding 'I-' tags. 
Another would be to randomly add a linebreak in some of the Email examples (i.e. when generating a dataset) as to introduce the 'I-' tag for Emails.

I have not tested it very thoroughly yet and perhaps this behaviour is expected as CoNLL formats are always multi line entities in which case the quick and dirty fix on the `predict` output would fit the issue perfectly.

**Comment by amaiya** [comment]
With transformer embeddings, if there is an email on a single line, it will get tokenized like this right now when the training set is adjusted by `fix_tokenize` (if the transformer tokenizer splits up the email into tokens):
```python
([['sundar', '@', 'google', '.', 'com']],
 [['B-EMAIL', 'I-EMAIL', 'I-EMAIL', 'I-EMAIL', 'I-EMAIL']])
```

Is the problem that the model you're training is not learning to classify the `I-EMAIL` entities correctly?   Or is the training set not being adjusted to the above in the first place?

If the former, it is possible to ensure the email is kept together on a single line with a single label even if using transformer embeddings (in which case you could use custom tokenization scheme for specific problems instead of just following what the transformer tokenizer does).   I think the code change for this would be fairly straightforward after the most recent update for Roberta.

**Comment by amaiya** [comment]
Hi:  Is the problem that the model you're training is not learning to classify the `I-EMAIL` entities correctly (because there is no registered 'I-EMAIL' tag)?

**Comment by Niekvdplas** [comment]
I am not sure what to put as value to the argument `custom_tokenizer`. Without this argument the model performs not too well now and this might be due to the missing of the `custom_tokenizer` argument at the moment or that this isn't the right way to handle the issue. At the moment I am assuming that the `I-EMAIL` tag is not known as a possible label to the model (as it tries to fill up the 'I-' tag with one from another label) and perhaps this issue can be circumvented as a whole while retaining the regular tokenization scheme?

**Comment by amaiya** [comment]
There was a bug in the last push (the default tokenizer needed to be updated).  The `develop` branch was updated with fix. The new default tokenizer will keep email addresses together and split tokens like `99.9%` as `99.9 %`, which seems to be consistent with the tokenization scheme used in the CoNLL datasets.  You should not typically need to use a `custom_tokenizer` unless there are special circumstances.

- Can you please try it again on your dataset and let me know results/performance?  I am not seeing any performance degradation on my end (in fact, validation results for some models look improved).
- If you're still seeing a problem, please let me know if you are you able to share your dataset either by posting a link here or sharing a private link via email?

**Comment by Niekvdplas** [comment]
I'll try some more in the morning, otherwise I'll Email you a mock of my dataset

**Comment by amaiya** [comment]
Updates were released in v0.31.0.  Feel free to reply to this issue if any problems.

**Comment by Niekvdplas** [comment]
Hi @amaiya , sorry I've been away. The changes you've implemented do work however are not a perfect fit for me. I'll try and explain my theory on why the introduction of 'I-' labels for every 'B-' label would in some if not a lot of the cases be better.

Say I have this string: "NL49INGA0684739664" which is an IBAN number often used in financial systems. The tokens if tokenized normally would be : `[NL, 49, RABO and 0684739664]`. My theory is that because Transformers use the context around a token, 'NL' would have a higher probability of being assigned B-IBAN because of the surrounding tokens which are a subword of the original word giving extra context to the model. Another potential problem I see is what would happen if there exists a blank space inbetween the IBAN, Email or any other entity would it have more difficulty correctly classifying the entity? 

I hope you are able to somewhat understand what I am saying here as I have some difficulty describing my thinking.
 
Please be aware that this issue might only be applicable to me and that the solution you've made is a general good solution.

**Comment by amaiya** [comment]
Hi @Niekvdplas :  The new tokenization scheme still fits your use case.  The new tokenization scheme only affects the units that the BiLSTM operates on, not the `transformers` model.  The token "NL49INGA0684739664" will still get assigned a word embedding based on the vector for "NL" (first subword) based on surrounding context.  The BiLSTM model operates on this word embedding and returns a single prediction for "NL49INGA0684739664" (which makes sense because it is a cohesive unit).  

The new scheme also puts more control in the hands of the user.  If you **do** want the BiLSTM model to make a separate prediction for each subword in the IBAN number (even though this is more work for the model and probably harder to do), then you can simply re-tokenize the input dataset as you need and, when making predictions, implement a custom tokenizer (e.g., a lambda function that accepts a string and returns a list of tokens) that is consistent with how you re-tokenized the training set and based on how you want IBAN  numbers tokenized.
