### ISSUE TITLE
Summarization 

### ISSUE THREAD

**Issue by akald** [amaiya/ktrain#446]
Hi on ktrain 0.31 (latest version) when I run text summarisation I get a different (worse) result:

"Information on upcoming or currently active missions not mentioned below would be welcome. Cassini is a joint NASA/ESA project designed to accomplish exploration of the Saturnian system. JPL has developed a backup plan for the first resolved images of an asteroid, Gaspra, while in transit to Jupiter".

**Comment by amaiya** [comment]
What version of ktrain were you using before?

**Comment by akald** [comment]
0.3 but I hadn't tested it on any version prior to 0.31

**Comment by amaiya** [comment]
So, you're saying you're getting a different summarization result on 0.31 vs 0.30?

**Comment by amaiya** [comment]
Using the same original code for both **ktrain** and **transformers** (same versions of libraries) returns a different summarization result now (vice 2020).  My only guess is that the model itself has changed (or perhaps some downstream `transformers` dependency has changed).   You might try a different BART model (e.g., `sshleifer/distilbart-cnn-12-6`).  It doesn't look like anything in **ktrain** (or  **transformers** library code) changed to cause this different result, though. You can consider investigating this further on your own and submit a PR if it affects anything in **ktrain** (or reply to this thread if you find the cause is something else).
