### ISSUE TITLE
Multilingual model from HuggingFace

### ISSUE THREAD

**Issue by Alexookah** [amaiya/ktrain#51]
Congratulations for this awesome easy to use the library.

I am using the Greek language to test the multilingual bert model from hugging face

In the preprocessing method for train and test test data.

`train_data = t.preprocess_train(x_train, y_train)`

I am getting an output:

`preprocessing train...
language: en`

this is a bit misleading that the language identified is language 'English'.

I think that bert tokenizer handles the preprocessing and does not need to know the language input. The language detection is for the automatic model selection (english / multilingual).
Is that correct? 
So if I am correct the language identified does not need to be printed out when using hugging's Face multilingual model?

**Comment by amaiya** [comment]
@Alexookah You are exactly right.  In the *ktrain* `Transformer` interface to Hugging Face transformer library, the pretrained model is explicitly specified by user so auto-detection of language doesn't come into play and perhaps should be removed in the next release. 

As an aside, in the alternative API in *ktrain* for text classification using `texts_from_*` and `text_classifier` functions, the auto-detection of language is used to select the BERT model: English vs. Chinese vs. Multilingual.  It is also used to do appropriate preprocessing of language (e.g., Chinese) in the case of non-BERT models. However, if the auto-detection is wrong, the language can be explicitly specified with the `lang` paramter to `texts_from_*` functions in order to ensure the appropriate model and preprocessing is employed.

**Comment by amaiya** [comment]
Actually, there is no auto-detection of language when using `Transformer` class for the reasons stated in my earlier reply.  The incorrect printing of `en` is a minor bug.  It does not affect preprocessing or training at all, but should not be displayed/printed. It will be removed in next release.  Thanks for posting issue..
