### ISSUE TITLE
Can't get layer output for transformers

### ISSUE THREAD

**Issue by lambdaofgod** [amaiya/ktrain#61]
First of all thanks for your work, your library seems really useful and has reasonable API.

## Problem

I want to extract features using transformer models. I tried this for bert and distilbert models and I get an error: `AttributeError: Layer bert is not connected, no input to return.`

I was wondering whether this was the case because model wasn't compiled: but after running lr_find it still throws this error.

Reproducible example:
```
categories = ['alt.atheism', 'soc.religion.christian',
             'comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train',
   categories=categories, shuffle=True, random_state=42)
test_b = fetch_20newsgroups(subset='test',
   categories=categories, shuffle=True, random_state=42)

print('size of training set: %s' % (len(train_b['data'])))
print('size of validation set: %s' % (len(test_b['data'])))
print('classes: %s' % (train_b.target_names))

x_train = train_b.data
y_train = train_b.target
x_test = test_b.data
y_test = test_b.target



import ktrain
from ktrain import text
MODEL_NAME = 'bert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=200, classes=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)

learner.lr_find(show_plot=True, max_epochs=1)

learner.layer_output(2, example_id=5, use_val=True)

```

**Comment by amaiya** [comment]
Thanks for your comments.  

Yes, that doesn't seem to work. It might be because Hugging Face transformer models are built using TF2 subclassing API, which apparently [doesn't support getting intermediate outputs](https://github.com/tensorflow/tensorflow/issues/30955).  

If you're trying to extract features, you could try using the Transformer library directly and either modifying the configuration to return hidden states or using a different class that returns the raw hidden states by design.  Both are [discussed in this thread](https://github.com/huggingface/transformers/issues/1950).
