### ISSUE TITLE
Getting multiple errors from tensorflow after trying to predict on data.

### ISSUE THREAD

**Issue by Niekvdplas** [amaiya/ktrain#67]
So I am able to preprocess and learn on my train and test data but after calling predictor.predict(...), three warnings are thrown:

2020-02-25 00:40:58.462939: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-02-25 00:41:03.791849: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_2]]
2020-02-25 00:41:03.791848: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]

I read somewhere it is because it is getting a next item when it actually cant, so i.e. 139 / 2 = 69.5, so it should go to 69 but someone assumes it rounds up instead of down.

I would like to know if there is a solution for this :-)

N.B. this was my done on my local machine running python 3.7, cuda 10.1, tensorflow 2.1.0rc1 and this was my code if someone would like to reproduce it!

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' 
import tensorflow as tf
import ktrain

predictor = ktrain.load_predictor(r"C:/Users/{{name}}/Documents/Predictors/preddi")

predictor.predict("texttexttext")

**Comment by amaiya** [comment]
As far as I can tell, this appears to be some sort of TensorFlow 2 issue that happens when you create a tf.Dataset using `from_generator`.  See [this issue](https://github.com/tensorflow/tensorflow/issues/32817) and [this issue](https://github.com/tensorflow/tensorflow/issues/35100) on TensorFlow's GitHub repo.  It started being visible in *ktrain* when we started using `from_generator` to create datasets for transformer models.  

As noted in [this issue](https://github.com/tensorflow/tensorflow/issues/35100),  it may be related to a memory leak in TensorFlow, but may only be a problem with larger numbers of epochs.  Rounding down isn't a solution isn't a solution and causes other problems in TF2.

It's a warning that doesn't affect results in *ktrain*, though.   You'll notice that `predictor.predict` still correctly generates predictions.   Also, I'm not able to reproduce this in local Jupyter notebooks or on Google Colab.  For me, it only appears when at iPython prompt or stand-alone script.

If you want to suppress it,  you can add this to the top of your script:
```
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
```
