### ISSUE TITLE
How to set up a custom language classifier?

### ISSUE THREAD

**Issue by ErikTromp** [amaiya/ktrain#75]
I am trying to get a Dutch Transformer model up an running fo classification with my own custom Dutch dataset. I get hit with an error saying that language could not be detected. Is there any way I can feed it a language so it doesn't have to detect? Or am I doing something else wrong here as it did recognize language when loading the data.

```
>>> import ktrain
using Keras version: 2.2.4-tf
>>> from ktrain import text
>>> (x_train, y_train), (x_test, y_test), preproc  = text.texts_from_csv('emotions.csv', text_column='text', encoding='utf8', label_columns=['labels'])
language: nl
Word Counts: 288635
Nrows: 256617
256617 train sequences
train sequence lengths:
        mean : 14
        95percentile : 25
        99percentile : 40
x_train shape: (256617,400)
y_train shape: (256617, 9)
28514 test sequences
test sequence lengths:
        mean : 14
        95percentile : 25
        99percentile : 40
x_test shape: (28514,400)
y_test shape: (28514, 9)
>>> t = text.Transformer('bert-base-dutch-cased', maxlen=256)
>>> trn = t.preprocess_train(x_train, y_train)
preprocessing train...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Erik\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py", line 946, in preprocess_train
    tseq = super().preprocess_train(texts, y=y, mode=mode, verbose=verbose)
  File "C:\Users\Erik\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py", line 764, in preprocess_train
    if self.lang is None and mode=='train': self.lang = TU.detect_lang(texts)
  File "C:\Users\Erik\Anaconda3\lib\site-packages\ktrain\text\textutils.py", line 206, in detect_lang
    raise Exception('could not detect language in random sample of %s docs.'  % (sample_size))
Exception: could not detect language in random sample of 32 docs.
```

**Comment by amaiya** [comment]
There are two different ways to do BERT-based text classification in *ktrain*: 1) the [basic API](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/IMDb-BERT.ipynb) and the 2) [Transformer API](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb)


In the basic API, `texts_from_csv` (and `texts_from_folder` and `texts_from_array`) not only load the data but also preprocess the data into word IDs.  In the Transformer API, the `preprocess_train` and `preprocess_test` methods expect a list of raw texts in the form of arrays.  However, in your case,  you're supplying these methods with data that has been already preprocessed into word IDs by `texts_from_csv`.   The language detection is complaining because it can't detect language from a list of integers. (Also, since you did not specify  a `preprocess_mode` in `texts_from_csv`, your data was not preprocessed correctly for `Trasnformer` models anyways.)

If you want to use the Transformer API, you'll need to populate `(x_train, y_train)` and `(x_test, y_test)` yourself by loading the columns from your CSV into arrays using something like this:

```
import pandas as pd
df = pd.read_csv('emotions.csv',, encoding='utf-8', sep=',')
texts = df[text_column].fillna('fillna').values
labels = df[label_column].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(texts, labels, test_size=0.1, random_state=42)
```

I will leave this issue open for now to make this more clear in the tutorial notebooks and error messages.  Thanks for posting the question.

Also, please be sure to use the latest version of *ktrain* (v0.10.), as the implementation of `preprocess_train` and `preprocess_test` in this version allows `y_train` and `y_test` to be a single column of string labels, which may be the case in your example.

**Comment by ErikTromp** [comment]
Yep that did it, for those interested in a full snippet:

```
import ktrain
from ktrain import text
from sklearn.model_selection import train_test_split
import pandas as pd

df = pd.read_csv('emotions_class.csv', encoding='utf-8', sep=';')
texts = df['text'].fillna('fillna').values
labels = df['labels_text'].values
x_train, x_test, y_train, y_test = train_test_split(texts, labels, test_size=0.3, random_state=42)

MODEL_NAME = 'bert-base-dutch-cased'
t = text.Transformer(MODEL_NAME, maxlen=64, class_names=list(set(labels)))
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=8)
```
