### ISSUE TITLE
TypeError for serialize model to JSON

### ISSUE THREAD

**Issue by zirubak** [amaiya/ktrain#76]
I made serialize model to JSON using save() in predictor.py. 

```python
    def save(self, fname):

        if U.is_ner(model=self.model):
            from .text.ner import crf_loss
            self.model.compile(loss=crf_loss, optimizer=U.DEFAULT_OPT)

        # JH
        self.model.save(fname+".h5", save_format='h5')
        #self.model.save(fname, save_format='h5')

        # serialize model to JSON
        # JH
        model_json = self.model.to_json()
        print(model_json)
        with open(fname+".json", "w") as json_file:
            json_file.write(model_json)
```

And read it using
```python
json_file = open('/Users/jbaek/ws/Transformers_Example/ktrain/Multi_Label_Text_Classification/model-test-2.json', 'r')
# json_file = open('./model/model_aws/'+'model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
```

Return this error:

### TypeError: tuple indices must be integers or slices, not list

How to solve this issue? I try to deploy this model to AWS Sagemaker Endpoint. 

- Reference site:
> https://aws.amazon.com/blogs/machine-learning/deploy-trained-keras-or-tensorflow-models-using-amazon-sagemaker/

**Comment by amaiya** [comment]
Hugging Face Transformer models [are saved differently](https://github.com/huggingface/transformers/issues/2645) than other Keras models.  See `ktrain.text.predictor.save` method:
```python
self.model.save_pretrained(fpath)
```

I don't have any experience with SageMaker.  However, the reference site you're using is over a year old and doesn't look  compatible with TensorFlow 2.  Since the underlying Transformer model  in *ktrain* is just a normal Hugging Face TF2 model, you might try asking questions about saving/deploying on SageMaker as an issue on the Hugging Face transformer GitHub repo.

**Comment by zirubak** [comment]
@amaiya Thanks for your information. 

What is the most common way to deploy Transformer models is created by Ktrain? 
Sagemaker is just one option for me. 

Can I use TensorFlow Servings?

**Comment by amaiya** [comment]
The underlying models in *ktrain* are just TensorFlow Keras models (e.g., using either Sequential API, Functional API, or Subclassing API), so you should be able to deploy however you would normally deploy a TensorFlow 2 model. I believe some have deployed using TensorFlow Serving.  Others have [setup a Flask app to serve their model](https://github.com/amaiya/ktrain/issues/37#issuecomment-568085054) using the *ktrain* `Predictor` instances that wrap their model and preprocessing steps.
