### ISSUE TITLE
Can't load H5 file which is created in Ktrain using load_model in Keras

### ISSUE THREAD

**Issue by zirubak** [amaiya/ktrain#89]
Hi 

I can't load H5 file which is created in Ktrain using load_model in Keras. 

I checked a similar issue in this here but the issue was created with old version. 

Would you please check this issue with TF2.1 and the latest Keras version? 

My goal is to create a model using Ktrain( I love Ktrain to much.. :) ) and deploy using Tensorflow Serving or Sagemager Endpoint to predict using REST API. 

Welcome to share a good example. 
I spend more than a week to solve this issue. :(

Thanks

Here is Code and Logs. 

**from keras.models import load_model
 
model_loaded = load_model('./ktrain/ktrain_save_mode.h5/tf_model.h5')**

Using TensorFlow backend.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-362640505b2c> in <module>
      1 from keras.models import load_model
      2 
----> 3 model_loaded = load_model('./ktrain/ktrain_save_mode.h5/tf_model.h5')

~/anaconda3/envs/Transformers-For-Eagle/lib/python3.7/site-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
    490                 os.remove(tmp_filepath)
    491             return res
--> 492         return load_function(*args, **kwargs)
    493 
    494     return load_wrapper

~/anaconda3/envs/Transformers-For-Eagle/lib/python3.7/site-packages/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    582     if H5Dict.is_supported_type(filepath):
    583         with H5Dict(filepath, mode='r') as h5dict:
--> 584             model = _deserialize_model(h5dict, custom_objects, compile)
    585     elif hasattr(filepath, 'write') and callable(filepath.write):
    586         def load_function(h5file):

~/anaconda3/envs/Transformers-For-Eagle/lib/python3.7/site-packages/keras/engine/saving.py in _deserialize_model(h5dict, custom_objects, compile)
    268         return obj
    269 
--> 270     model_config = h5dict['model_config']
    271     if model_config is None:
    272         raise ValueError('No model found in config.')

~/anaconda3/envs/Transformers-For-Eagle/lib/python3.7/site-packages/keras/utils/io_utils.py in __getitem__(self, attr)
    316             else:
    317                 if self.read_only:
--> 318                     raise ValueError('Cannot create group in read-only mode.')
    319                 val = H5Dict(self.data.create_group(attr))
    320         return val

**ValueError: Cannot create group in read-only mode.**

**Comment by amaiya** [comment]
Hi @zirubak Everything  should work in TF 2.1.0.  I think your issue is that the Keras `load_model` function will not work with `transformers` library, as pretrained transformer models need to be loaded in a special way.   It's easiest to load the model either using the `Predictor` API in *ktrain* or via `learner.load_model`.  Both of these function essentially invoke something like `TFBertForSequenceClassification.from_pretrained(fpath)` to load the model (in the case of BERT).

Assuming you saved a `Predictor` instance via `predictor.save` method after you trained your model, I would try this:

```python
reloaded_predictor = ktrain.load_predictor('./ktrain/ktrain_save_mode.h5')
model = reloaded_predictor.model
```

See STEP 5 in [this tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb) for more details on saving and reloading predictors.

Alternatively,  you could just load the model directly using the `transformers` library using `<ModelClass>.from_pretrained` where <ModelClass> is the Class of the model you saved (e.g., `TFDistilBertForSequenceClassification` or `TFBertForSequenceClassification`.  Make sure you point to the folder containing the model and JSON config (as opposed to the model file itself like you did in your example), as this is what the `transformers` library requires, I believe.
